export const DESTINATIONS = [
    "Japan",
    "Thailand",
    "Mexico",
    "Italy",
    "India",
    "France",
    "Morocco",
    "Peru",
    "South Korea",
    "Spain",
    "Turkey",
    "Vietnam",
    "Greece",
    "Brazil",
    "Colombia",
]

export const TIMEZONE_OFFSETS: Record<string, number> = {
    Japan: 9,
    Thailand: 7,
    Mexico: -6,
    Italy: 1,
    India: 5.5,
    France: 1,
    Morocco: 1,
    Peru: -5,
    "South Korea": 9,
    Spain: 1,
    Turkey: 3,
    Vietnam: 7,
    Greece: 2,
    Brazil: -3,
    Colombia: -5,
}
