export type Language = 'en' | 'pt' | 'es' | 'fr' | 'de' | 'it' | 'zh' | 'ja'

export const LANGUAGES = [
  { code: 'en' as Language, name: 'English', flag: '🇬🇧' },
  { code: 'pt' as Language, name: 'Português', flag: '🇵🇹' },
  { code: 'es' as Language, name: 'Español', flag: '🇪🇸' },
  { code: 'fr' as Language, name: 'Français', flag: '🇫🇷' },
  { code: 'de' as Language, name: 'Deutsch', flag: '🇩🇪' },
  { code: 'it' as Language, name: 'Italiano', flag: '🇮🇹' },
  { code: 'zh' as Language, name: '中文', flag: '🇨🇳' },
  { code: 'ja' as Language, name: '日本語', flag: '🇯🇵' },
]

export function getLanguage(): Language {
  if (typeof window === 'undefined') return 'en'
  return (localStorage.getItem('language') as Language) || 'en'
}

export function setLanguage(lang: Language) {
  if (typeof window === 'undefined') return
  localStorage.setItem('language', lang)
}

export const translations = {
  en: {
    // Onboarding
    setupProfile: "Let's set up your nutrition profile",
    aboutYou: "About You",
    apiKey: "OpenAI API Key",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "Required for AI meal planning and dish discovery. Your key is stored locally in your device.",
    name: "Name",
    namePlaceholder: "Your name",
    age: "Age",
    sex: "Sex",
    male: "Male",
    female: "Female",
    other: "Other",
    height: "Height (cm)",
    weight: "Weight (kg)",
    goal: "Goal",
    goalSelectPlaceholder: "Select your goal",
    loseWeight: "Lose Weight",
    maintain: "Maintain",
    gainMuscle: "Gain Muscle",
    allergies: "Allergies & Intolerances",
    allergiesDescription: "Select all that apply",
    selectAllergiesDesc: "Select any allergies or food intolerances. This helps us flag unsafe dishes.",
    safetyGuardrail: "Safety Guardrail Active",
    aiWillNever: "AI will never recommend dishes containing:",
    preferences: "Preferences",
    tripDetails: "Trip Details",
    localCuisine: "Local Cuisine",
    mealPlan: "Meal Plan",
    goals: "Goals",
    nutritionalGoal: "Nutritional Goal",
    dailyCalorieTarget: "Daily Calorie Target",
    waterTarget: "Water Target",
    dietaryPreferences: "Dietary Preferences",
    selectPreferencesDesc: "Select your dietary preferences to personalize meal recommendations.",
    review: "Review & Finish",
    back: "Back",
    next: "Next",
    finish: "Start Journey",
    
    // Settings
    settings: "Settings",
    openaiApiKey: "OpenAI API Key",
    profile: "Profile",
    calTarget: "Cal Target",
    saveProfile: "Save Profile",
    saveAllergies: "Save Allergies",
    dangerZone: "Danger Zone",
    dangerZoneDescription: "Clear all local data including profile, trips, and meal logs.",
    clearAllData: "Clear All Data",
    theme: "Theme",
    themeDescription: "Switch between light and dark mode.",
    lightMode: "☀️ Light Mode",
    darkMode: "🌙 Dark Mode",
    language: "Language",
    languageDescription: "Choose your preferred language.",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "Key configured",
    
    // Common
    save: "Save",
  },
  pt: {
    // Onboarding
    setupProfile: "Vamos configurar o seu perfil nutricional",
    aboutYou: "Sobre Você",
    apiKey: "Chave API OpenAI",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "Necessária para planeamento de refeições e descoberta de pratos. A sua chave é armazenada localmente no seu dispositivo.",
    name: "Nome",
    namePlaceholder: "O seu nome",
    age: "Idade",
    sex: "Sexo",
    male: "Masculino",
    female: "Feminino",
    other: "Outro",
    height: "Altura (cm)",
    weight: "Peso (kg)",
    goal: "Objetivo",
    goalSelectPlaceholder: "Selecione o seu objetivo",
    loseWeight: "Perder Peso",
    maintain: "Manter",
    gainMuscle: "Ganhar Músculo",
    allergies: "Alergias e Intolerâncias",
    allergiesDescription: "Selecione todas as que se aplicam",
    selectAllergiesDesc: "Selecione quaisquer alergias ou intolerâncias alimentares. Isto ajuda-nos a sinalizar pratos inseguros.",
    safetyGuardrail: "Proteção de Segurança Ativa",
    aiWillNever: "A IA nunca recomendará pratos contendo:",
    preferences: "Preferências",
    tripDetails: "Detalhes da Viagem",
    localCuisine: "Cozinha Local",
    mealPlan: "Plano de Refeições",
    goals: "Objetivos",
    nutritionalGoal: "Objetivo Nutricional",
    dailyCalorieTarget: "Meta Diária de Calorias",
    waterTarget: "Meta de Água",
    dietaryPreferences: "Preferências Alimentares",
    selectPreferencesDesc: "Selecione as suas preferências alimentares para personalizar as recomendações de refeições.",
    review: "Rever e Concluir",
    back: "Voltar",
    next: "Próximo",
    finish: "Iniciar Jornada",
    
    // Settings
    settings: "Definições",
    openaiApiKey: "Chave API OpenAI",
    profile: "Perfil",
    calTarget: "Meta Cal",
    saveProfile: "Guardar Perfil",
    saveAllergies: "Guardar Alergias",
    dangerZone: "Zona de Perigo",
    dangerZoneDescription: "Limpar todos os dados locais incluindo perfil, viagens e registos de refeições.",
    clearAllData: "Limpar Todos os Dados",
    theme: "Tema",
    themeDescription: "Alternar entre modo claro e escuro.",
    lightMode: "☀️ Modo Claro",
    darkMode: "🌙 Modo Escuro",
    language: "Idioma",
    languageDescription: "Escolha o seu idioma preferido.",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "Chave configurada",
    
    // Common
    save: "Guardar",
  },
  es: {
    setupProfile: "Configuremos tu perfil nutricional",
    aboutYou: "Sobre Ti",
    apiKey: "Clave API OpenAI",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "Necesaria para planificación de comidas y descubrimiento de platos. Tu clave se almacena localmente.",
    name: "Nombre",
    namePlaceholder: "Tu nombre",
    age: "Edad",
    sex: "Sexo",
    male: "Masculino",
    female: "Femenino",
    other: "Otro",
    height: "Altura (cm)",
    weight: "Peso (kg)",
    goal: "Objetivo",
    goalSelectPlaceholder: "Selecciona tu objetivo",
    loseWeight: "Perder Peso",
    maintain: "Mantener",
    gainMuscle: "Ganar Músculo",
    allergies: "Alergias e Intolerancias",
    allergiesDescription: "Selecciona todas las que apliquen",
    selectAllergiesDesc: "Selecciona cualquier alergia o intolerancia alimentaria. Esto nos ayuda a marcar platos no seguros.",
    safetyGuardrail: "Protección de Seguridad Activa",
    aiWillNever: "La IA nunca recomendará platos que contengan:",
    preferences: "Preferencias",
    tripDetails: "Detalles del Viaje",
    localCuisine: "Cocina Local",
    mealPlan: "Plan de Comidas",
    goals: "Objetivos",
    nutritionalGoal: "Objetivo Nutricional",
    dailyCalorieTarget: "Meta Diaria de Calorías",
    waterTarget: "Meta de Agua",
    dietaryPreferences: "Preferencias Dietéticas",
    selectPreferencesDesc: "Selecciona tus preferencias dietéticas para personalizar las recomendaciones de comidas.",
    review: "Revisar y Finalizar",
    back: "Atrás",
    next: "Siguiente",
    finish: "Comenzar Viaje",
    settings: "Configuración",
    openaiApiKey: "Clave API OpenAI",
    profile: "Perfil",
    calTarget: "Meta Cal",
    saveProfile: "Guardar Perfil",
    saveAllergies: "Guardar Alergias",
    dangerZone: "Zona de Peligro",
    dangerZoneDescription: "Borrar todos los datos locales incluyendo perfil, viajes y registros de comidas.",
    clearAllData: "Borrar Todos los Datos",
    theme: "Tema",
    themeDescription: "Cambiar entre modo claro y oscuro.",
    lightMode: "☀️ Modo Claro",
    darkMode: "🌙 Modo Oscuro",
    language: "Idioma",
    languageDescription: "Elige tu idioma preferido.",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "Clave configurada",
    save: "Guardar",
  },
  fr: {
    setupProfile: "Configurons votre profil nutritionnel",
    aboutYou: "À Propos de Vous",
    apiKey: "Clé API OpenAI",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "Nécessaire pour la planification des repas et la découverte de plats. Votre clé est stockée localement.",
    name: "Nom",
    namePlaceholder: "Votre nom",
    age: "Âge",
    sex: "Sexe",
    male: "Masculin",
    female: "Féminin",
    other: "Autre",
    height: "Taille (cm)",
    weight: "Poids (kg)",
    goal: "Objectif",
    goalSelectPlaceholder: "Sélectionnez votre objectif",
    loseWeight: "Perdre du Poids",
    maintain: "Maintenir",
    gainMuscle: "Gagner du Muscle",
    allergies: "Allergies et Intolérances",
    allergiesDescription: "Sélectionnez toutes celles qui s'appliquent",
    selectAllergiesDesc: "Sélectionnez toutes les allergies ou intolérances alimentaires. Cela nous aide à signaler les plats dangereux.",
    safetyGuardrail: "Protection de Sécurité Active",
    aiWillNever: "L'IA ne recommandera jamais de plats contenant:",
    preferences: "Préférences",
    tripDetails: "Détails du Voyage",
    localCuisine: "Cuisine Locale",
    mealPlan: "Plan de Repas",
    goals: "Objectifs",
    nutritionalGoal: "Objectif Nutritionnel",
    dailyCalorieTarget: "Objectif Calorique Quotidien",
    waterTarget: "Objectif d'Eau",
    dietaryPreferences: "Préférences Alimentaires",
    selectPreferencesDesc: "Sélectionnez vos préférences alimentaires pour personnaliser les recommandations de repas.",
    review: "Réviser et Terminer",
    back: "Retour",
    next: "Suivant",
    finish: "Commencer le Voyage",
    settings: "Paramètres",
    openaiApiKey: "Clé API OpenAI",
    profile: "Profil",
    calTarget: "Cible Cal",
    saveProfile: "Enregistrer le Profil",
    saveAllergies: "Enregistrer les Allergies",
    dangerZone: "Zone de Danger",
    dangerZoneDescription: "Effacer toutes les données locales y compris le profil, les voyages et les journaux de repas.",
    clearAllData: "Effacer Toutes les Données",
    theme: "Thème",
    themeDescription: "Basculer entre le mode clair et sombre.",
    lightMode: "☀️ Mode Clair",
    darkMode: "🌙 Mode Sombre",
    language: "Langue",
    languageDescription: "Choisissez votre langue préférée.",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "Clé configurée",
    save: "Enregistrer",
  },
  de: {
    setupProfile: "Lass uns dein Ernährungsprofil einrichten",
    aboutYou: "Über Dich",
    apiKey: "OpenAI API-Schlüssel",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "Erforderlich für Essensplanung und Gerichtentdeckung. Dein Schlüssel wird lokal gespeichert.",
    name: "Name",
    namePlaceholder: "Dein Name",
    age: "Alter",
    sex: "Geschlecht",
    male: "Männlich",
    female: "Weiblich",
    other: "Andere",
    height: "Größe (cm)",
    weight: "Gewicht (kg)",
    goal: "Ziel",
    goalSelectPlaceholder: "Wähle dein Ziel",
    loseWeight: "Gewicht Verlieren",
    maintain: "Halten",
    gainMuscle: "Muskeln Aufbauen",
    allergies: "Allergien & Unverträglichkeiten",
    allergiesDescription: "Wähle alle zutreffenden",
    selectAllergiesDesc: "Wähle alle Allergien oder Lebensmittelunverträglichkeiten. Dies hilft uns, unsichere Gerichte zu markieren.",
    safetyGuardrail: "Sicherheitsschutz Aktiv",
    aiWillNever: "Die KI wird niemals Gerichte empfehlen, die enthalten:",
    preferences: "Präferenzen",
    tripDetails: "Reisedetails",
    localCuisine: "Lokale Küche",
    mealPlan: "Essensplan",
    goals: "Ziele",
    nutritionalGoal: "Ernährungsziel",
    dailyCalorieTarget: "Tägliches Kalorienziel",
    waterTarget: "Wasserziel",
    dietaryPreferences: "Ernährungspräferenzen",
    selectPreferencesDesc: "Wähle deine Ernährungspräferenzen, um die Essensempfehlungen zu personalisieren.",
    review: "Überprüfen & Abschließen",
    back: "Zurück",
    next: "Weiter",
    finish: "Reise Starten",
    settings: "Einstellungen",
    openaiApiKey: "OpenAI API-Schlüssel",
    profile: "Profil",
    calTarget: "Kal-Ziel",
    saveProfile: "Profil Speichern",
    saveAllergies: "Allergien Speichern",
    dangerZone: "Gefahrenzone",
    dangerZoneDescription: "Alle lokalen Daten löschen, einschließlich Profil, Reisen und Mahlzeitenprotokolle.",
    clearAllData: "Alle Daten Löschen",
    theme: "Thema",
    themeDescription: "Zwischen hellem und dunklem Modus wechseln.",
    lightMode: "☀️ Heller Modus",
    darkMode: "🌙 Dunkler Modus",
    language: "Sprache",
    languageDescription: "Wähle deine bevorzugte Sprache.",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "Schlüssel konfiguriert",
    save: "Speichern",
  },
  it: {
    setupProfile: "Configuriamo il tuo profilo nutrizionale",
    aboutYou: "Su di Te",
    apiKey: "Chiave API OpenAI",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "Necessaria per la pianificazione dei pasti e la scoperta di piatti. La tua chiave è memorizzata localmente.",
    name: "Nome",
    namePlaceholder: "Il tuo nome",
    age: "Età",
    sex: "Sesso",
    male: "Maschile",
    female: "Femminile",
    other: "Altro",
    height: "Altezza (cm)",
    weight: "Peso (kg)",
    goal: "Obiettivo",
    goalSelectPlaceholder: "Seleziona il tuo obiettivo",
    loseWeight: "Perdere Peso",
    maintain: "Mantenere",
    gainMuscle: "Guadagnare Muscoli",
    allergies: "Allergie e Intolleranze",
    allergiesDescription: "Seleziona tutte quelle che si applicano",
    selectAllergiesDesc: "Seleziona qualsiasi allergia o intolleranza alimentare. Questo ci aiuta a segnalare piatti non sicuri.",
    safetyGuardrail: "Protezione di Sicurezza Attiva",
    aiWillNever: "L'IA non consiglierà mai piatti contenenti:",
    preferences: "Preferenze",
    tripDetails: "Dettagli del Viaggio",
    localCuisine: "Cucina Locale",
    mealPlan: "Piano Pasti",
    goals: "Obiettivi",
    nutritionalGoal: "Obiettivo Nutrizionale",
    dailyCalorieTarget: "Obiettivo Calorico Giornaliero",
    waterTarget: "Obiettivo d'Acqua",
    dietaryPreferences: "Preferenze Dietetiche",
    selectPreferencesDesc: "Seleziona le tue preferenze dietetiche per personalizzare i consigli sui pasti.",
    review: "Rivedi e Termina",
    back: "Indietro",
    next: "Avanti",
    finish: "Inizia il Viaggio",
    settings: "Impostazioni",
    openaiApiKey: "Chiave API OpenAI",
    profile: "Profilo",
    calTarget: "Obiettivo Cal",
    saveProfile: "Salva Profilo",
    saveAllergies: "Salva Allergie",
    dangerZone: "Zona di Pericolo",
    dangerZoneDescription: "Cancella tutti i dati locali inclusi profilo, viaggi e registri dei pasti.",
    clearAllData: "Cancella Tutti i Dati",
    theme: "Tema",
    themeDescription: "Cambia tra modalità chiara e scura.",
    lightMode: "☀️ Modalità Chiara",
    darkMode: "🌙 Modalità Scura",
    language: "Lingua",
    languageDescription: "Scegli la tua lingua preferita.",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "Chiave configurata",
    save: "Salva",
  },
  zh: {
    setupProfile: "让我们设置您的营养档案",
    aboutYou: "关于您",
    apiKey: "OpenAI API密钥",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "AI餐饮规划和菜肴发现所需。您的密钥将本地存储。",
    name: "姓名",
    namePlaceholder: "您的姓名",
    age: "年龄",
    sex: "性别",
    male: "男性",
    female: "女性",
    other: "其他",
    height: "身高 (cm)",
    weight: "体重 (kg)",
    goal: "目标",
    goalSelectPlaceholder: "选择您的目标",
    loseWeight: "减重",
    maintain: "保持",
    gainMuscle: "增肌",
    allergies: "过敏和不耐受",
    allergiesDescription: "选择所有适用项",
    selectAllergiesDesc: "选择任何过敏或食物不耐受。这有助于我们标记不安全的菜肴。",
    safetyGuardrail: "安全保护已激活",
    aiWillNever: "AI永远不会推荐包含以下成分的菜肴：",
    preferences: "偏好",
    tripDetails: "旅行详情",
    localCuisine: "当地美食",
    mealPlan: "餐饮计划",
    goals: "目标",
    nutritionalGoal: "营养目标",
    dailyCalorieTarget: "每日卡路里目标",
    waterTarget: "水摄入目标",
    dietaryPreferences: "饮食偏好",
    selectPreferencesDesc: "选择您的饮食偏好以个性化餐饮推荐。",
    review: "审查并完成",
    back: "返回",
    next: "下一步",
    finish: "开始旅程",
    settings: "设置",
    openaiApiKey: "OpenAI API密钥",
    profile: "个人资料",
    calTarget: "卡路里目标",
    saveProfile: "保存个人资料",
    saveAllergies: "保存过敏信息",
    dangerZone: "危险区域",
    dangerZoneDescription: "清除所有本地数据，包括个人资料、旅行和餐饮记录。",
    clearAllData: "清除所有数据",
    theme: "主题",
    themeDescription: "在浅色和深色模式之间切换。",
    lightMode: "☀️ 浅色模式",
    darkMode: "🌙 深色模式",
    language: "语言",
    languageDescription: "选择您的首选语言。",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "密钥已配置",
    save: "保存",
  },
  ja: {
    setupProfile: "栄養プロフィールを設定しましょう",
    aboutYou: "あなたについて",
    apiKey: "OpenAI APIキー",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "AI食事計画と料理発見に必要です。キーはローカルに保存されます。",
    name: "名前",
    namePlaceholder: "あなたの名前",
    age: "年齢",
    sex: "性別",
    male: "男性",
    female: "女性",
    other: "その他",
    height: "身長 (cm)",
    weight: "体重 (kg)",
    goal: "目標",
    goalSelectPlaceholder: "目標を選択",
    loseWeight: "減量",
    maintain: "維持",
    gainMuscle: "筋肉増強",
    allergies: "アレルギーと不耐性",
    allergiesDescription: "該当するものをすべて選択",
    selectAllergiesDesc: "アレルギーや食物不耐性を選択してください。これにより、安全でない料理を警告します。",
    safetyGuardrail: "安全保護が有効",
    aiWillNever: "AIは以下を含む料理を推奨しません：",
    preferences: "好み",
    tripDetails: "旅行の詳細",
    localCuisine: "地元料理",
    mealPlan: "食事計画",
    goals: "目標",
    nutritionalGoal: "栄養目標",
    dailyCalorieTarget: "1日のカロリー目標",
    waterTarget: "水分摂取目標",
    dietaryPreferences: "食事の好み",
    selectPreferencesDesc: "食事の好みを選択して、食事の推奨をパーソナライズします。",
    review: "確認して完了",
    back: "戻る",
    next: "次へ",
    finish: "旅を始める",
    settings: "設定",
    openaiApiKey: "OpenAI APIキー",
    profile: "プロフィール",
    calTarget: "カロリー目標",
    saveProfile: "プロフィールを保存",
    saveAllergies: "アレルギーを保存",
    dangerZone: "危険ゾーン",
    dangerZoneDescription: "プロフィール、旅行、食事記録を含むすべてのローカルデータを消去します。",
    clearAllData: "すべてのデータを消去",
    theme: "テーマ",
    themeDescription: "ライトモードとダークモードを切り替えます。",
    lightMode: "☀️ ライトモード",
    darkMode: "🌙 ダークモード",
    language: "言語",
    languageDescription: "お好みの言語を選択してください。",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "キーが設定されました",
    save: "保存",
  }
}

export function t(key: keyof typeof translations.en, lang?: Language): string {
  const language = lang || getLanguage()
  return translations[language][key] || translations.en[key]
}
