export type Language = 'en' | 'pt-PT' | 'pt-BR' | 'es' | 'fr' | 'de' | 'it' | 'zh' | 'ja'

export const LANGUAGES = [
  { code: 'en' as Language, name: 'English', flag: '🇬🇧' },
  { code: 'pt-PT' as Language, name: 'Português (PT)', flag: '🇵🇹' },
  { code: 'pt-BR' as Language, name: 'Português (BR)', flag: '🇧🇷' },
  { code: 'es' as Language, name: 'Español', flag: '🇪🇸' },
  { code: 'fr' as Language, name: 'Français', flag: '🇫🇷' },
  { code: 'de' as Language, name: 'Deutsch', flag: '🇩🇪' },
  { code: 'it' as Language, name: 'Italiano', flag: '🇮🇹' },
  { code: 'zh' as Language, name: '中文', flag: '🇨🇳' },
  { code: 'ja' as Language, name: '日本語', flag: '🇯🇵' },
]

export function getLanguage(): Language {
  if (typeof window === 'undefined') return 'en'
  return (localStorage.getItem('language') as Language) || 'en'
}

export function setLanguage(lang: Language) {
  if (typeof window === 'undefined') return
  localStorage.setItem('language', lang)
  // Dispatch custom event to notify components of language change
  window.dispatchEvent(new CustomEvent('languageChanged', { detail: lang }))
}

export const translations = {
  en: {
    // Onboarding
    setupProfile: "Let's set up your nutrition profile",
    aboutYou: "About You",
    apiKey: "OpenAI API Key",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "Required for AI meal planning and dish discovery. Your key is stored locally in your device.",
    name: "Name",
    namePlaceholder: "Your name",
    age: "Age",
    sex: "Sex",
    male: "Male",
    female: "Female",
    other: "Other",
    height: "Height (cm)",
    weight: "Weight (kg)",
    goal: "Goal",
    goalSelectPlaceholder: "Select your goal",
    loseWeight: "Lose Weight",
    maintain: "Maintain",
    gainMuscle: "Gain Muscle",
    allergies: "Allergies & Intolerances",
    allergiesDescription: "Select all that apply",
    selectAllergiesDesc: "Select any allergies or food intolerances. This helps us flag unsafe dishes.",
    safetyGuardrail: "Safety Guardrail Active",
    aiWillNever: "AI will never recommend dishes containing:",
    preferences: "Preferences",
    tripDetails: "Trip Details",
    localCuisine: "Local Cuisine",
    mealPlan: "Meal Plan",
    goals: "Goals",
    nutritionalGoal: "Nutritional Goal",
    dailyCalorieTarget: "Daily Calorie Target",
    waterTarget: "Water Target",
    dietaryPreferences: "Dietary Preferences",
    selectPreferencesDesc: "Select your dietary preferences to personalize meal recommendations.",
    departureCity: "Departure City",
    departureCityPlaceholder: "e.g. New York",
    destinationCountry: "Destination Country",
    selectDestination: "Select destination",
    departure: "Departure",
    arrival: "Arrival",
    departureTime: "Departure Time",
    arrivalTime: "Arrival Time",
    timezoneShift: "Timezone Shift",
    timezoneDesc: "is UTC",
    mealTimesAdjusted: ". Meal times will be adjusted.",
    selectDishes: "Select dishes you'd like to try in",
    selected: "selected",
    discoveringCuisine: "Discovering local cuisine...",
    aiCrafting: "AI is crafting your personalized meal plan...",
    calories: "Calories",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    review: "Review & Finish",
    back: "Back",
    next: "Next",
    finish: "Start Journey",
    planConfirmation: "Plan Confirmation",
    choosePlanPath: "Choose how you want to proceed with your meal plan.",
    continueWithProvidedPlan: "Continue with provided plan",
    requestLocalDietitianReview: "Request local dietitian review",
    simulatingDietitianReview: "Simulating dietitian review...",
    dietitianReviewComplete: "Review complete.",
    reviewedByLocalSpecialist: "Reviewed by a local specialist.",
    proceedToApp: "Proceed to App",
    noDetailedPlanToReview: "No detailed plan is available to review. You can still continue.",
    dietitianReviewedSuccessBy: "Reviewed successfully by",
    reviewCompleted: "Review completed",
    nutritionistReviewLabel: "Local nutritionist verification",
    
    // Settings
    settings: "Settings",
    openaiApiKey: "OpenAI API Key",
    profile: "Profile",
    calTarget: "Cal Target",
    saveProfile: "Save Profile",
    saveAllergies: "Save Allergies",
    dangerZone: "Danger Zone",
    dangerZoneDescription: "Clear all local data including profile, trips, and meal logs.",
    clearAllData: "Clear All Data",
    theme: "Theme",
    themeDescription: "Switch between light and dark mode.",
    lightMode: "☀️ Light Mode",
    darkMode: "🌙 Dark Mode",
    language: "Language",
    languageDescription: "Choose your preferred language.",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "Key configured",
    
    // Allergy labels
    gluten: "Gluten",
    dairy: "Dairy",
    eggs: "Eggs",
    peanuts: "Peanuts",
    treeNuts: "Tree Nuts",
    soy: "Soy",
    fish: "Fish",
    shellfish: "Shellfish",
    wheat: "Wheat",
    sesame: "Sesame",
    notKnow: "Not Know",
    
    // Diet preference labels
    vegetarian: "Vegetarian",
    vegan: "Vegan",
    keto: "Keto",
    paleo: "Paleo",
    mediterranean: "Mediterranean",
    lowCarb: "Low Carb",
    lowFat: "Low Fat",
    halal: "Halal",
    kosher: "Kosher",
    noPreference: "No Preference",
    
    // Custom adding
    addAllergy: "Add an allergy",
    addPreference: "Add a preference",
    add: "Add",
    alreadyAdded: "Already added",
    contains: "Contains",
    allergens: "Allergens",
    added: "added",
    couldNotGeneratePlan: "Could not generate meal plan. Using offline template.",
    
    // Navigation
    navHome: "Home",
    navTrip: "Trip",
    navAdd: "Add",
    navLog: "Log",
    navSettings: "Settings",
    
    // Dashboard
    welcomeBack: "Welcome back,",
    traveler: "Traveler",
    kcalRemaining: "kcal remaining",
    water: "Water",
    steps: "Steps",
    todaysMeals: "Today's Meals",
    logged: "logged",
    noMealsYet: "No meals logged yet today",
    logFirstMeal: "Log Your First Meal",
    offPlan: "Off-plan",
    planAdjusted: "Plan Adjusted",
    planAdjustedDesc: "You had an off-plan meal. Your remaining meals have been recalculated to keep you on track.",
    
    // Meal Logger
    dailyLog: "Daily Log",
    meals: "Meals",
    activity: "Activity",
    pleaseEnterMealName: "Please enter a meal name",
    negativeValuesError: "Nutritional values cannot be negative",
    mealLogged: "Meal logged!",
    mealRemoved: "Meal removed",
    addManualMeal: "Add Manual Meal",
    mealName: "Meal Name",
    mealType: "Meal Type",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    snack: "Snack",
    notes: "Notes",
    cancel: "Cancel",
    addMeal: "Add Meal",
    addMealManually: "Add Meal Manually",
    ofTarget: "target",
    stepCount: "Step Count",
    activityLevel: "Activity Level",
    sedentary: "Sedentary",
    deskWork: "Desk work",
    lightActivity: "Light",
    walkingTours: "Walking tours",
    moderate: "Moderate",
    hikingCycling: "Hiking, cycling",
    activeLevel: "Active",
    sportsIntense: "Sports, intense",
    activityNotes: "Activity Notes",
    
    // Meal Analysis
    analyzeMeal: "Analyze Meal",
    analyzeDesc: "Take a photo of your meal for AI-powered nutritional analysis",
    dishName: "Dish Name",
    dishNamePlaceholder: "e.g., Pad Thai, Pizza Margherita...",
    dishNameOptional: "(optional - helps improve accuracy)",
    analysisMode: "Analysis Mode",
    mealPhoto: "Meal Photo",
    menuPhoto: "Menu Photo",
    manualEntry: "Manual Entry",
    mealPhotoDesc: "Analyze a photo of your meal",
    menuPhotoDesc: "Extract nutrition from a menu",
    manualEntryDesc: "Manually log meals, water, and activity",
    improvesAccuracy: "Dish name improves nutrition accuracy",
    basedOnCuisine: "Based on cuisine",
    menuDetected: "Menu items detected",
    selectItemsToLog: "Select items to log",
    captureOrUpload: "Capture or upload a meal photo",
    camera: "Camera",
    uploadPhoto: "Upload",
    analyzing: "Analyzing...",
    retake: "Retake",
    allergenWarning: "Allergen Warning",
    detectedIngredients: "Detected Ingredients",
    confidence: "confidence",
    logThisMeal: "Log This Meal",
    couldNotAnalyze: "Could not analyze photo. Check your API key in Settings.",
    pleaseWaitAnalysis: "Please wait for current analysis to complete",
    failedToReadImage: "Failed to read image file",
    couldNotLoadDishes: "Could not load local dishes. Using offline data.",
    pleaseCompleteTripDetails: "Please complete trip details first",
    mealLoggedSuccess: "Meal logged successfully!",
    allergenDetected: "Allergen detected",
    
    // Trip Planning
    noTripPlanned: "No Trip Planned Yet",
    noTripDesc: "Complete your profile setup to start planning your culinary adventure.",
    yourTrip: "Your Trip",
    activeBadge: "Active",
    origin: "Origin",
    timezone: "Timezone",
    mustTryDishes: "Must-Try Dishes",
    mustTryBeverages: "Must-Try Beverages",
    noDishesSelected: "No dishes selected yet.",
    noBeveragesSelected: "No recommended beverages for this destination.",
    alcoholic: "Alcoholic",
    nonAlcoholic: "Non-alcoholic",
    worthTrying: "Worth trying",
    dailyMealPlan: "Daily Meal Plan",
    
    // Settings extras
    apiKeyDescLong: "Required for meal photo analysis, local dish discovery, and AI meal planning. Your key is stored locally in your browser.",
    allDataCleared: "All data cleared. Refreshing...",
    
    // Common
    save: "Save",
    addEntry: "Add Entry",
    addEntryDesc: "Add meals, water, and activity using photos or manual entry",
    dailySummary: "Daily Summary",
    
    // Welcome Screen
    welcome: "Welcome!",
    howWouldYouLikeToBegin: "How would you like to begin?",
    startFresh: "Start Fresh",
    setUpProfile: "Set up your profile and preferences from scratch. Perfect for first-time users.",
    haveNutritionistPlan: "I Have a Nutritionist Plan",
    uploadPlanDescription: "Upload your personalized meal plan from your nutritionist to get started quickly.",
    uploading: "Importing...",
    uploadPlan: "Upload Plan (JSON)",
    acceptsJsonFormat: "Accepts JSON format with profile and meal plan data",
    downloadSampleFormat: "Download sample format",
    dontWorryAdjustLater: "Don't worry, you can always adjust your preferences later in Settings",
  },
  "pt-PT": {
    // Onboarding
    setupProfile: "Vamos configurar o seu perfil nutricional",
    aboutYou: "Sobre Si",
    apiKey: "Chave API OpenAI",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "Necessária para planeamento de refeições e descoberta de pratos. A sua chave é armazenada localmente no seu dispositivo.",
    name: "Nome",
    namePlaceholder: "O seu nome",
    age: "Idade",
    sex: "Sexo",
    male: "Masculino",
    female: "Feminino",
    other: "Outro",
    height: "Altura (cm)",
    weight: "Peso (kg)",
    goal: "Objetivo",
    goalSelectPlaceholder: "Selecione o seu objetivo",
    loseWeight: "Perder Peso",
    maintain: "Manter",
    gainMuscle: "Ganhar Músculo",
    allergies: "Alergias e Intolerâncias",
    allergiesDescription: "Selecione todas as que se aplicam",
    selectAllergiesDesc: "Selecione quaisquer alergias ou intolerâncias alimentares. Isto ajuda-nos a sinalizar pratos inseguros.",
    safetyGuardrail: "Proteção de Segurança Ativa",
    aiWillNever: "A IA nunca recomendará pratos contendo:",
    preferences: "Preferências",
    tripDetails: "Detalhes da Viagem",
    localCuisine: "Cozinha Local",
    mealPlan: "Plano de Refeições",
    goals: "Objetivos",
    nutritionalGoal: "Objetivo Nutricional",
    dailyCalorieTarget: "Meta Diária de Calorias",
    waterTarget: "Meta de Água",
    dietaryPreferences: "Preferências Alimentares",
    selectPreferencesDesc: "Selecione as suas preferências alimentares para personalizar as recomendações de refeições.",
    departureCity: "Cidade de Partida",
    departureCityPlaceholder: "ex. Lisboa",
    destinationCountry: "País de Destino",
    selectDestination: "Selecione o destino",
    departure: "Partida",
    arrival: "Chegada",
    departureTime: "Hora de Partida",
    arrivalTime: "Hora de Chegada",
    timezoneShift: "Mudança de Fuso Horário",
    timezoneDesc: "está em UTC",
    mealTimesAdjusted: ". Os horários das refeições serão ajustados.",
    selectDishes: "Selecione pratos que gostaria de experimentar em",
    selected: "selecionados",
    discoveringCuisine: "A descobrir a cozinha local...",
    aiCrafting: "A IA está a criar o seu plano de refeições personalizado...",
    calories: "Calorias",
    protein: "Proteína",
    carbs: "Hidratos",
    fat: "Gordura",
    review: "Rever e Concluir",
    back: "Voltar",
    next: "Próximo",
    finish: "Iniciar Jornada",
    planConfirmation: "Confirmação do Plano",
    choosePlanPath: "Escolha como pretende avançar com o plano de refeições.",
    continueWithProvidedPlan: "Continuar com o plano fornecido",
    requestLocalDietitianReview: "Pedir verificação de nutricionista local",
    simulatingDietitianReview: "A simular verificação da nutricionista...",
    dietitianReviewComplete: "Verificação concluída.",
    reviewedByLocalSpecialist: "Revisto por um especialista local.",
    proceedToApp: "Prosseguir para a app",
    noDetailedPlanToReview: "Não existe um plano detalhado para rever. Pode continuar.",
    dietitianReviewedSuccessBy: "Revisto com sucesso por",
    reviewCompleted: "Revisão concluída",
    nutritionistReviewLabel: "Verificação por nutricionista local",
    
    // Settings
    settings: "Definições",
    openaiApiKey: "Chave API OpenAI",
    profile: "Perfil",
    calTarget: "Meta Cal",
    saveProfile: "Guardar Perfil",
    saveAllergies: "Guardar Alergias",
    dangerZone: "Zona de Perigo",
    dangerZoneDescription: "Limpar todos os dados locais incluindo perfil, viagens e registos de refeições.",
    clearAllData: "Limpar Todos os Dados",
    theme: "Tema",
    themeDescription: "Alternar entre modo claro e escuro.",
    lightMode: "☀️ Modo Claro",
    darkMode: "🌙 Modo Escuro",
    language: "Idioma",
    languageDescription: "Escolha o seu idioma preferido.",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "Chave configurada",
    
    // Allergy labels
    gluten: "Glúten",
    dairy: "Laticínios",
    eggs: "Ovos",
    peanuts: "Amendoins",
    treeNuts: "Frutos Secos",
    soy: "Soja",
    fish: "Peixe",
    shellfish: "Marisco",
    wheat: "Trigo",
    sesame: "Sésamo",
    notKnow: "Não Sei",
    
    // Diet preference labels
    vegetarian: "Vegetariano",
    vegan: "Vegano",
    keto: "Keto",
    paleo: "Paleo",
    mediterranean: "Mediterrânica",
    lowCarb: "Baixo Carbo",
    lowFat: "Baixa Gordura",
    halal: "Halal",
    kosher: "Kosher",
    noPreference: "Sem Preferência",
    
    // Custom adding
    addAllergy: "Adicionar alergia",
    addPreference: "Adicionar preferência",
    add: "Adicionar",
    alreadyAdded: "Já adicionado",
    contains: "Contém",
    allergens: "Alergénios",
    added: "adicionado",
    couldNotGeneratePlan: "Não foi possível gerar o plano de refeições. A usar modelo offline.",
    
    // Navigation
    navHome: "Início",
    navTrip: "Viagem",
    navAdd: "Adicionar",
    navLog: "Registo",
    navSettings: "Definições",
    
    // Dashboard
    welcomeBack: "Bem-vindo de volta,",
    traveler: "Viajante",
    kcalRemaining: "kcal restantes",
    water: "Água",
    steps: "Passos",
    todaysMeals: "Refeições de Hoje",
    logged: "registadas",
    noMealsYet: "Nenhuma refeição registada hoje",
    logFirstMeal: "Registar Primeira Refeição",
    offPlan: "Fora do plano",
    planAdjusted: "Plano Ajustado",
    planAdjustedDesc: "Teve uma refeição fora do plano. As restantes refeições foram recalculadas para o manter no caminho certo.",
    
    // Meal Logger
    dailyLog: "Registo Diário",
    meals: "Refeições",
    activity: "Atividade",
    pleaseEnterMealName: "Por favor introduza o nome da refeição",
    negativeValuesError: "Os valores nutricionais não podem ser negativos",
    mealLogged: "Refeição registada!",
    mealRemoved: "Refeição removida",
    addManualMeal: "Adicionar Refeição Manual",
    mealName: "Nome da Refeição",
    mealType: "Tipo de Refeição",
    breakfast: "Pequeno-Almoço",
    lunch: "Almoço",
    dinner: "Jantar",
    snack: "Lanche",
    notes: "Notas",
    cancel: "Cancelar",
    addMeal: "Adicionar Refeição",
    addMealManually: "Adicionar Refeição Manualmente",
    ofTarget: "meta",
    stepCount: "Contagem de Passos",
    activityLevel: "Nível de Atividade",
    sedentary: "Sedentário",
    deskWork: "Trabalho de secretária",
    lightActivity: "Leve",
    walkingTours: "Passeios a pé",
    moderate: "Moderado",
    hikingCycling: "Caminhada, ciclismo",
    activeLevel: "Ativo",
    sportsIntense: "Desportos, intenso",
    activityNotes: "Notas de Atividade",
    
    // Meal Analysis
    analyzeMeal: "Analisar Refeição",
    analyzeDesc: "Tire uma foto da sua refeição para análise nutricional com IA",
    dishName: "Nome do Prato",
    dishNamePlaceholder: "ex: Bacalhau à Brás, Francesinha...",
    dishNameOptional: "(opcional - melhora a precisão)",
    analysisMode: "Modo de Análise",
    mealPhoto: "Foto da Refeição",
    menuPhoto: "Foto do Menu",
    manualEntry: "Entrada Manual",
    mealPhotoDesc: "Analisar uma foto da sua refeição",
    manualEntryDesc: "Registar manualmente refeições, água e atividade",
    menuPhotoDesc: "Extrair nutrição de um menu",
    improvesAccuracy: "Nome do prato melhora a precisão nutricional",
    basedOnCuisine: "Baseado na culinária",
    menuDetected: "Itens do menu detectados",
    selectItemsToLog: "Selecione itens para registar",
    captureOrUpload: "Capture ou carregue uma foto de refeição",
    camera: "Câmara",
    uploadPhoto: "Carregar",
    analyzing: "A analisar...",
    retake: "Repetir",
    allergenWarning: "Alerta de Alergénio",
    detectedIngredients: "Ingredientes Detetados",
    confidence: "confiança",
    logThisMeal: "Registar Esta Refeição",
    couldNotAnalyze: "Não foi possível analisar a foto. Verifique a sua chave API nas Definições.",
    pleaseWaitAnalysis: "Por favor aguarde até a análise atual estar completa",
    failedToReadImage: "Falha ao ler o ficheiro de imagem",
    couldNotLoadDishes: "Não foi possível carregar pratos locais. A usar dados offline.",
    pleaseCompleteTripDetails: "Por favor complete os detalhes da viagem primeiro",
    mealLoggedSuccess: "Refeição registada com sucesso!",
    allergenDetected: "Alergénio detetado",
    
    // Trip Planning
    noTripPlanned: "Nenhuma Viagem Planeada",
    noTripDesc: "Complete a configuração do seu perfil para começar a planear a sua aventura culinária.",
    yourTrip: "A Sua Viagem",
    activeBadge: "Ativa",
    origin: "Origem",
    timezone: "Fuso Horário",
    mustTryDishes: "Pratos Imperdíveis",
    mustTryBeverages: "Bebidas Imperdíveis",
    noDishesSelected: "Nenhum prato selecionado ainda.",
    noBeveragesSelected: "Nenhuma bebida recomendada para este destino.",
    alcoholic: "Alcoólica",
    nonAlcoholic: "Sem álcool",
    worthTrying: "Vale a pena",
    dailyMealPlan: "Plano Diário de Refeições",
    
    // Settings extras
    apiKeyDescLong: "Necessária para análise de fotos de refeições, descoberta de pratos locais e planeamento de refeições com IA. A sua chave é armazenada localmente no seu navegador.",
    allDataCleared: "Todos os dados apagados. A atualizar...",
    
    // Common
    save: "Guardar",
    addEntry: "Adicionar Entrada",
    addEntryDesc: "Adicionar refeições, água e atividade usando fotos ou entrada manual",
    dailySummary: "Resumo Diário",
    
    // Welcome Screen
    welcome: "Bem-vindo!",
    howWouldYouLikeToBegin: "Como gostaria de começar?",
    startFresh: "Começar do Zero",
    setUpProfile: "Configure o seu perfil e preferências de raiz. Perfeito para novos utilizadores.",
    haveNutritionistPlan: "Tenho um Plano de Nutricionista",
    uploadPlanDescription: "Carregue o seu plano alimentar personalizado do seu nutricionista para começar rapidamente.",
    uploading: "A importar...",
    uploadPlan: "Carregar Plano (JSON)",
    acceptsJsonFormat: "Aceita formato JSON com dados de perfil e plano alimentar",
    downloadSampleFormat: "Descarregar formato exemplo",
    dontWorryAdjustLater: "Não se preocupe, pode sempre ajustar as suas preferências mais tarde nas Definições",
    howWouldYouLikeToBegin: "¿Cómo te gustaría empezar?",
    startFresh: "Empezar de Cero",
    setUpProfile: "Configura tu perfil y preferencias desde cero. Perfecto para nuevos usuarios.",
    haveNutritionistPlan: "Tengo un Plan de Nutricionista",
    uploadPlanDescription: "Sube tu plan alimentario personalizado de tu nutricionista para empezar rápidamente.",
    uploading: "Importando...",
    uploadPlan: "Subir Plan (JSON)",
    acceptsJsonFormat: "Acepta formato JSON con datos de perfil y plan alimentario",
    downloadSampleFormat: "Descargar formato ejemplo",
    dontWorryAdjustLater: "No te preocupes, siempre puedes ajustar tus preferencias más tarde en Configuración",
    addEntry: "Adicionar Entrada",
    dailySummary: "Resumo Diário",
    
    // Welcome Screen
    welcome: "Bem-vindo!",
    howWouldYouLikeToBegin: "Como gostaria de começar?",
    startFresh: "Começar do Zero",
    setUpProfile: "Configure o seu perfil e preferências de raiz. Perfeito para novos utilizadores.",
    haveNutritionistPlan: "Tenho um Plano de Nutricionista",
    uploadPlanDescription: "Carregue o seu plano alimentar personalizado do seu nutricionista para começar rapidamente.",
    uploading: "A importar...",
    uploadPlan: "Carregar Plano (JSON)",
    acceptsJsonFormat: "Aceita formato JSON com dados de perfil e plano alimentar",
    downloadSampleFormat: "Descarregar formato exemplo",
    dontWorryAdjustLater: "Não se preocupe, pode sempre ajustar as suas preferências mais tarde nas Definições",
  },
  "pt-BR": {
    // Onboarding
    setupProfile: "Vamos configurar seu perfil nutricional",
    aboutYou: "Sobre Você",
    apiKey: "Chave API OpenAI",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "Necessária para planejamento de refeições e descoberta de pratos. Sua chave é armazenada localmente no seu dispositivo.",
    name: "Nome",
    namePlaceholder: "Seu nome",
    age: "Idade",
    sex: "Sexo",
    male: "Masculino",
    female: "Feminino",
    other: "Outro",
    height: "Altura (cm)",
    weight: "Peso (kg)",
    goal: "Objetivo",
    goalSelectPlaceholder: "Selecione seu objetivo",
    loseWeight: "Perder Peso",
    maintain: "Manter",
    gainMuscle: "Ganhar Músculo",
    allergies: "Alergias e Intolerâncias",
    allergiesDescription: "Selecione todas que se aplicam",
    selectAllergiesDesc: "Selecione quaisquer alergias ou intolerâncias alimentares. Isso nos ajuda a sinalizar pratos inseguros.",
    safetyGuardrail: "Proteção de Segurança Ativa",
    aiWillNever: "A IA nunca recomendará pratos contendo:",
    preferences: "Preferências",
    tripDetails: "Detalhes da Viagem",
    localCuisine: "Cozinha Local",
    mealPlan: "Plano de Refeições",
    goals: "Objetivos",
    nutritionalGoal: "Objetivo Nutricional",
    dailyCalorieTarget: "Meta Diária de Calorias",
    waterTarget: "Meta de Água",
    dietaryPreferences: "Preferências Alimentares",
    selectPreferencesDesc: "Selecione suas preferências alimentares para personalizar as recomendações de refeições.",
    departureCity: "Cidade de Partida",
    departureCityPlaceholder: "ex. São Paulo",
    destinationCountry: "País de Destino",
    selectDestination: "Selecione o destino",
    departure: "Partida",
    arrival: "Chegada",
    departureTime: "Horário de Partida",
    arrivalTime: "Horário de Chegada",
    timezoneShift: "Mudança de Fuso Horário",
    timezoneDesc: "está em UTC",
    mealTimesAdjusted: ". Os horários das refeições serão ajustados.",
    selectDishes: "Selecione pratos que gostaria de experimentar em",
    selected: "selecionados",
    discoveringCuisine: "Descobrindo a cozinha local...",
    aiCrafting: "A IA está criando seu plano de refeições personalizado...",
    calories: "Calorias",
    protein: "Proteína",
    carbs: "Carboidratos",
    fat: "Gordura",
    review: "Revisar e Concluir",
    back: "Voltar",
    next: "Próximo",
    finish: "Iniciar Jornada",
    planConfirmation: "Confirmação do Plano",
    choosePlanPath: "Escolha como deseja continuar com o plano de refeições.",
    continueWithProvidedPlan: "Continuar com o plano fornecido",
    requestLocalDietitianReview: "Solicitar revisão de nutricionista local",
    simulatingDietitianReview: "Simulando revisão da nutricionista...",
    dietitianReviewComplete: "Revisão concluída.",
    reviewedByLocalSpecialist: "Revisado por um especialista local.",
    proceedToApp: "Prosseguir para o app",
    noDetailedPlanToReview: "Não há plano detalhado para revisar. Você ainda pode continuar.",
    dietitianReviewedSuccessBy: "Revisado com sucesso por",
    reviewCompleted: "Revisão concluída",
    nutritionistReviewLabel: "Verificação por nutricionista local",
    
    // Settings
    settings: "Configurações",
    openaiApiKey: "Chave API OpenAI",
    profile: "Perfil",
    calTarget: "Meta Cal",
    saveProfile: "Salvar Perfil",
    saveAllergies: "Salvar Alergias",
    dangerZone: "Zona de Perigo",
    dangerZoneDescription: "Limpar todos os dados locais incluindo perfil, viagens e registros de refeições.",
    clearAllData: "Limpar Todos os Dados",
    theme: "Tema",
    themeDescription: "Alternar entre modo claro e escuro.",
    lightMode: "☀️ Modo Claro",
    darkMode: "🌙 Modo Escuro",
    language: "Idioma",
    languageDescription: "Escolha seu idioma preferido.",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "Chave configurada",
    
    // Allergy labels
    gluten: "Glúten",
    dairy: "Laticínios",
    eggs: "Ovos",
    peanuts: "Amendoins",
    treeNuts: "Nozes",
    soy: "Soja",
    fish: "Peixe",
    shellfish: "Frutos do Mar",
    wheat: "Trigo",
    sesame: "Gergelim",
    notKnow: "Não Sei",
    
    // Diet preference labels
    vegetarian: "Vegetariano",
    vegan: "Vegano",
    keto: "Keto",
    paleo: "Paleo",
    mediterranean: "Mediterrânea",
    lowCarb: "Baixo Carbo",
    lowFat: "Baixa Gordura",
    halal: "Halal",
    kosher: "Kosher",
    noPreference: "Sem Preferência",
    
    // Custom adding
    addAllergy: "Adicionar alergia",
    addPreference: "Adicionar preferência",
    add: "Adicionar",
    alreadyAdded: "Já adicionado",
    contains: "Contém",
    allergens: "Alérgenos",
    added: "adicionado",
    couldNotGeneratePlan: "Não foi possível gerar o plano de refeições. Usando modelo offline.",
    
    // Navigation
    navHome: "Início",
    navTrip: "Viagem",
    navAdd: "Adicionar",
    navLog: "Registro",
    navSettings: "Configurações",
    
    // Dashboard
    welcomeBack: "Bem-vindo de volta,",
    traveler: "Viajante",
    kcalRemaining: "kcal restantes",
    water: "Água",
    steps: "Passos",
    todaysMeals: "Refeições de Hoje",
    logged: "registradas",
    noMealsYet: "Nenhuma refeição registrada hoje",
    logFirstMeal: "Registrar Primeira Refeição",
    offPlan: "Fora do plano",
    planAdjusted: "Plano Ajustado",
    planAdjustedDesc: "Você teve uma refeição fora do plano. Suas refeições restantes foram recalculadas para mantê-lo no caminho certo.",
    
    // Meal Logger
    dailyLog: "Registro Diário",
    meals: "Refeições",
    activity: "Atividade",
    pleaseEnterMealName: "Por favor insira o nome da refeição",
    negativeValuesError: "Os valores nutricionais não podem ser negativos",
    mealLogged: "Refeição registrada!",
    mealRemoved: "Refeição removida",
    addManualMeal: "Adicionar Refeição Manual",
    mealName: "Nome da Refeição",
    mealType: "Tipo de Refeição",
    breakfast: "Café da Manhã",
    lunch: "Almoço",
    dinner: "Jantar",
    snack: "Lanche",
    notes: "Notas",
    cancel: "Cancelar",
    addMeal: "Adicionar Refeição",
    addMealManually: "Adicionar Refeição Manualmente",
    ofTarget: "meta",
    stepCount: "Contagem de Passos",
    activityLevel: "Nível de Atividade",
    sedentary: "Sedentário",
    deskWork: "Trabalho de escritório",
    lightActivity: "Leve",
    walkingTours: "Passeios a pé",
    moderate: "Moderado",
    hikingCycling: "Caminhada, ciclismo",
    activeLevel: "Ativo",
    sportsIntense: "Esportes, intenso",
    activityNotes: "Notas de Atividade",
    
    // Meal Analysis
    analyzeMeal: "Analisar Refeição",
    analyzeDesc: "Tire uma foto da sua refeição para análise nutricional com IA",
    dishName: "Nome do Prato",
    dishNamePlaceholder: "ex: Feijoada, Moqueca...",
    dishNameOptional: "(opcional - melhora a precisão)",
    analysisMode: "Modo de Análise",
    mealPhoto: "Foto da Refeição",
    menuPhoto: "Foto do Cardápio",
    manualEntry: "Entrada Manual",
    mealPhotoDesc: "Analisar uma foto da sua refeição",
    manualEntryDesc: "Registrar manualmente refeições, água e atividade",
    menuPhotoDesc: "Extrair nutrição de um cardápio",
    improvesAccuracy: "Nome do prato melhora a precisão nutricional",
    basedOnCuisine: "Baseado na culinária",
    menuDetected: "Itens do cardápio detectados",
    selectItemsToLog: "Selecione itens para registrar",
    captureOrUpload: "Capture ou envie uma foto de refeição",
    camera: "Câmera",
    uploadPhoto: "Enviar",
    analyzing: "Analisando...",
    retake: "Refazer",
    allergenWarning: "Alerta de Alérgeno",
    detectedIngredients: "Ingredientes Detectados",
    confidence: "confiança",
    logThisMeal: "Registrar Esta Refeição",
    couldNotAnalyze: "Não foi possível analisar a foto. Verifique sua chave API nas Configurações.",
    pleaseWaitAnalysis: "Por favor aguarde até a análise atual estar completa",
    failedToReadImage: "Falha ao ler o arquivo de imagem",
    couldNotLoadDishes: "Não foi possível carregar pratos locais. Usando dados offline.",
    pleaseCompleteTripDetails: "Por favor complete os detalhes da viagem primeiro",
    mealLoggedSuccess: "Refeição registrada com sucesso!",
    allergenDetected: "Alérgeno detectado",
    
    // Trip Planning
    noTripPlanned: "Nenhuma Viagem Planejada",
    noTripDesc: "Complete a configuração do seu perfil para começar a planejar sua aventura culinária.",
    yourTrip: "Sua Viagem",
    activeBadge: "Ativa",
    origin: "Origem",
    timezone: "Fuso Horário",
    mustTryDishes: "Pratos Imperdíveis",
    mustTryBeverages: "Bebidas Imperdíveis",
    noDishesSelected: "Nenhum prato selecionado ainda.",
    noBeveragesSelected: "Nenhuma bebida recomendada para este destino.",
    alcoholic: "Alcoólica",
    nonAlcoholic: "Sem álcool",
    worthTrying: "Vale a pena",
    dailyMealPlan: "Plano Diário de Refeições",
    
    // Settings extras
    apiKeyDescLong: "Necessária para análise de fotos de refeições, descoberta de pratos locais e planejamento de refeições com IA. Sua chave é armazenada localmente no seu navegador.",
    allDataCleared: "Todos os dados limpos. Atualizando...",
    
    // Common
    save: "Salvar",
    addEntry: "Adicionar Entrada",
    addEntryDesc: "Adicionar refeições, água e atividade usando fotos ou entrada manual",
    dailySummary: "Resumo Diário",
    
    // Welcome Screen
    welcome: "Bem-vindo!",
    howWouldYouLikeToBegin: "Como você gostaria de começar?",
    startFresh: "Começar do Zero",
    setUpProfile: "Configure seu perfil e preferências do zero. Perfeito para novos usuários.",
    haveNutritionistPlan: "Tenho um Plano de Nutricionista",
    uploadPlanDescription: "Carregue seu plano alimentar personalizado do seu nutricionista para começar rapidamente.",
    uploading: "Importando...",
    uploadPlan: "Carregar Plano (JSON)",
    acceptsJsonFormat: "Aceita formato JSON com dados de perfil e plano alimentar",
    downloadSampleFormat: "Baixar formato exemplo",
    dontWorryAdjustLater: "Não se preocupe, você sempre pode ajustar suas preferências mais tarde nas Configurações",
  },
  es: {
    setupProfile: "Configuremos tu perfil nutricional",
    aboutYou: "Sobre Ti",
    apiKey: "Clave API OpenAI",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "Necesaria para planificación de comidas y descubrimiento de platos. Tu clave se almacena localmente.",
    name: "Nombre",
    namePlaceholder: "Tu nombre",
    age: "Edad",
    sex: "Sexo",
    male: "Masculino",
    female: "Femenino",
    other: "Otro",
    height: "Altura (cm)",
    weight: "Peso (kg)",
    goal: "Objetivo",
    goalSelectPlaceholder: "Selecciona tu objetivo",
    loseWeight: "Perder Peso",
    maintain: "Mantener",
    gainMuscle: "Ganar Músculo",
    allergies: "Alergias e Intolerancias",
    allergiesDescription: "Selecciona todas las que apliquen",
    selectAllergiesDesc: "Selecciona cualquier alergia o intolerancia alimentaria. Esto nos ayuda a marcar platos no seguros.",
    safetyGuardrail: "Protección de Seguridad Activa",
    aiWillNever: "La IA nunca recomendará platos que contengan:",
    preferences: "Preferencias",
    tripDetails: "Detalles del Viaje",
    localCuisine: "Cocina Local",
    mealPlan: "Plan de Comidas",
    goals: "Objetivos",
    nutritionalGoal: "Objetivo Nutricional",
    dailyCalorieTarget: "Meta Diaria de Calorías",
    waterTarget: "Meta de Agua",
    dietaryPreferences: "Preferencias Dietéticas",
    selectPreferencesDesc: "Selecciona tus preferencias dietéticas para personalizar las recomendaciones de comidas.",
    departureCity: "Ciudad de Partida",
    departureCityPlaceholder: "ej. Madrid",
    destinationCountry: "País de Destino",
    selectDestination: "Selecciona el destino",
    departure: "Partida",
    arrival: "Llegada",
    departureTime: "Hora de Partida",
    arrivalTime: "Hora de Llegada",
    timezoneShift: "Cambio de Zona Horaria",
    timezoneDesc: "está en UTC",
    mealTimesAdjusted: ". Los horarios de comida serán ajustados.",
    selectDishes: "Selecciona platos que te gustaría probar en",
    selected: "seleccionados",
    discoveringCuisine: "Descubriendo la cocina local...",
    aiCrafting: "La IA está creando tu plan de comidas personalizado...",
    calories: "Calorías",
    protein: "Proteína",
    carbs: "Carbohidratos",
    fat: "Grasa",
    review: "Revisar y Finalizar",
    back: "Atrás",
    next: "Siguiente",
    finish: "Comenzar Viaje",
    planConfirmation: "Confirmación del Plan",
    choosePlanPath: "Elige cómo quieres continuar con tu plan de comidas.",
    continueWithProvidedPlan: "Continuar con el plan proporcionado",
    requestLocalDietitianReview: "Solicitar revisión de nutricionista local",
    simulatingDietitianReview: "Simulando revisión de nutricionista...",
    dietitianReviewComplete: "Revisión completada.",
    reviewedByLocalSpecialist: "Revisado por un especialista local.",
    proceedToApp: "Continuar a la app",
    noDetailedPlanToReview: "No hay un plan detallado para revisar. Aún puedes continuar.",
    dietitianReviewedSuccessBy: "Revisado con éxito por",
    reviewCompleted: "Revisión completada",
    nutritionistReviewLabel: "Verificación por nutricionista local",
    settings: "Configuración",
    openaiApiKey: "Clave API OpenAI",
    profile: "Perfil",
    calTarget: "Meta Cal",
    saveProfile: "Guardar Perfil",
    saveAllergies: "Guardar Alergias",
    dangerZone: "Zona de Peligro",
    dangerZoneDescription: "Borrar todos los datos locales incluyendo perfil, viajes y registros de comidas.",
    clearAllData: "Borrar Todos los Datos",
    theme: "Tema",
    themeDescription: "Cambiar entre modo claro y oscuro.",
    lightMode: "☀️ Modo Claro",
    darkMode: "🌙 Modo Oscuro",
    language: "Idioma",
    languageDescription: "Elige tu idioma preferido.",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "Clave configurada",
    
    // Allergy labels
    gluten: "Gluten",
    dairy: "Lácteos",
    eggs: "Huevos",
    peanuts: "Cacahuetes",
    treeNuts: "Frutos Secos",
    soy: "Soja",
    fish: "Pescado",
    shellfish: "Mariscos",
    wheat: "Trigo",
    sesame: "Sésamo",
    notKnow: "No Sé",
    
    // Diet preference labels
    vegetarian: "Vegetariano",
    vegan: "Vegano",
    keto: "Keto",
    paleo: "Paleo",
    mediterranean: "Mediterránea",
    lowCarb: "Bajo en Carbohidratos",
    lowFat: "Bajo en Grasa",
    halal: "Halal",
    kosher: "Kosher",
    noPreference: "Sin Preferencia",
    
    // Custom adding
    addAllergy: "Añadir alergia",
    addPreference: "Añadir preferencia",
    add: "Añadir",
    alreadyAdded: "Ya añadido",
    contains: "Contiene",
    allergens: "Alérgenos",
    added: "añadido",
    couldNotGeneratePlan: "No se pudo generar el plan de comidas. Usando plantilla offline.",
    
    // Navigation
    navHome: "Inicio",
    navTrip: "Viaje",
    navAdd: "Añadir",
    navLog: "Registro",
    navSettings: "Ajustes",
    welcomeBack: "Bienvenido de vuelta,",
    traveler: "Viajero",
    kcalRemaining: "kcal restantes",
    water: "Agua",
    steps: "Pasos",
    todaysMeals: "Comidas de Hoy",
    logged: "registradas",
    noMealsYet: "No hay comidas registradas hoy",
    logFirstMeal: "Registra Tu Primera Comida",
    offPlan: "Fuera del plan",
    planAdjusted: "Plan Ajustado",
    planAdjustedDesc: "Tuviste una comida fuera del plan. Tus comidas restantes han sido recalculadas para mantenerte en el camino.",
    dailyLog: "Registro Diario",
    meals: "Comidas",
    activity: "Actividad",
    pleaseEnterMealName: "Por favor ingresa el nombre de la comida",
    negativeValuesError: "Los valores nutricionales no pueden ser negativos",
    mealLogged: "¡Comida registrada!",
    mealRemoved: "Comida eliminada",
    addManualMeal: "Agregar Comida Manual",
    mealName: "Nombre de Comida",
    mealType: "Tipo de Comida",
    breakfast: "Desayuno",
    lunch: "Almuerzo",
    dinner: "Cena",
    snack: "Merienda",
    notes: "Notas",
    cancel: "Cancelar",
    addMeal: "Agregar Comida",
    addMealManually: "Agregar Comida Manualmente",
    ofTarget: "meta",
    stepCount: "Conteo de Pasos",
    activityLevel: "Nivel de Actividad",
    sedentary: "Sedentario",
    deskWork: "Trabajo de escritorio",
    lightActivity: "Ligera",
    walkingTours: "Paseos a pie",
    moderate: "Moderada",
    hikingCycling: "Senderismo, ciclismo",
    activeLevel: "Activo",
    sportsIntense: "Deportes, intenso",
    activityNotes: "Notas de Actividad",
    analyzeMeal: "Analizar Comida",
    analyzeDesc: "Toma una foto de tu comida para análisis nutricional con IA",
    dishName: "Nombre del Plato",
    dishNamePlaceholder: "ej: Paella, Tortilla Española...",
    dishNameOptional: "(opcional - mejora la precisión)",
    analysisMode: "Modo de Análisis",
    mealPhoto: "Foto de Comida",
    menuPhoto: "Foto del Menú",
    manualEntry: "Entrada Manual",
    mealPhotoDesc: "Analizar una foto de tu comida",
    manualEntryDesc: "Registrar manualmente comidas, agua y actividad",
    menuPhotoDesc: "Extraer nutrición de un menú",
    improvesAccuracy: "El nombre del plato mejora la precisión nutricional",
    basedOnCuisine: "Basado en la cocina",
    menuDetected: "Elementos del menú detectados",
    selectItemsToLog: "Selecciona elementos para registrar",
    captureOrUpload: "Captura o sube una foto de comida",
    camera: "Cámara",
    uploadPhoto: "Subir",
    analyzing: "Analizando...",
    retake: "Repetir",
    allergenWarning: "Advertencia de Alérgeno",
    detectedIngredients: "Ingredientes Detectados",
    confidence: "confianza",
    logThisMeal: "Registrar Esta Comida",
    couldNotAnalyze: "No se pudo analizar la foto. Verifica tu clave API en Ajustes.",
    pleaseWaitAnalysis: "Por favor espera a que se complete el análisis actual",
    failedToReadImage: "Error al leer el archivo de imagen",
    couldNotLoadDishes: "No se pudieron cargar los platos locales. Usando datos sin conexión.",
    pleaseCompleteTripDetails: "Por favor completa los detalles del viaje primero",
    mealLoggedSuccess: "¡Comida registrada con éxito!",
    allergenDetected: "Alérgeno detectado",
    noTripPlanned: "Sin Viaje Planeado",
    noTripDesc: "Completa la configuración de tu perfil para comenzar a planificar tu aventura culinaria.",
    yourTrip: "Tu Viaje",
    activeBadge: "Activo",
    origin: "Origen",
    timezone: "Zona Horaria",
    mustTryDishes: "Platos Imprescindibles",
    mustTryBeverages: "Bebidas Imprescindibles",
    noDishesSelected: "Ningún plato seleccionado aún.",
    noBeveragesSelected: "No hay bebidas recomendadas para este destino.",
    alcoholic: "Alcohólica",
    nonAlcoholic: "Sin alcohol",
    worthTrying: "Vale la pena",
    dailyMealPlan: "Plan Diario de Comidas",
    apiKeyDescLong: "Necesaria para análisis de fotos de comidas, descubrimiento de platos locales y planificación de comidas con IA. Tu clave se almacena localmente en tu navegador.",
    allDataCleared: "Todos los datos borrados. Actualizando...",
    
    // Common
    save: "Guardar",
    addEntry: "Añadir Entrada",
    addEntryDesc: "Añadir comidas, agua y actividad usando fotos o entrada manual",
    dailySummary: "Resumen Diario",
  },
  fr: {
    setupProfile: "Configurons votre profil nutritionnel",
    aboutYou: "À Propos de Vous",
    apiKey: "Clé API OpenAI",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "Nécessaire pour la planification des repas et la découverte de plats. Votre clé est stockée localement.",
    name: "Nom",
    namePlaceholder: "Votre nom",
    age: "Âge",
    sex: "Sexe",
    male: "Masculin",
    female: "Féminin",
    other: "Autre",
    height: "Taille (cm)",
    weight: "Poids (kg)",
    goal: "Objectif",
    goalSelectPlaceholder: "Sélectionnez votre objectif",
    loseWeight: "Perdre du Poids",
    maintain: "Maintenir",
    gainMuscle: "Gagner du Muscle",
    allergies: "Allergies et Intolérances",
    allergiesDescription: "Sélectionnez toutes celles qui s'appliquent",
    selectAllergiesDesc: "Sélectionnez toutes les allergies ou intolérances alimentaires. Cela nous aide à signaler les plats dangereux.",
    safetyGuardrail: "Protection de Sécurité Active",
    aiWillNever: "L'IA ne recommandera jamais de plats contenant:",
    preferences: "Préférences",
    tripDetails: "Détails du Voyage",
    localCuisine: "Cuisine Locale",
    mealPlan: "Plan de Repas",
    goals: "Objectifs",
    nutritionalGoal: "Objectif Nutritionnel",
    dailyCalorieTarget: "Objectif Calorique Quotidien",
    waterTarget: "Objectif d'Eau",
    dietaryPreferences: "Préférences Alimentaires",
    selectPreferencesDesc: "Sélectionnez vos préférences alimentaires pour personnaliser les recommandations de repas.",
    departureCity: "Ville de Départ",
    departureCityPlaceholder: "ex. Paris",
    destinationCountry: "Pays de Destination",
    selectDestination: "Sélectionnez la destination",
    departure: "Départ",
    arrival: "Arrivée",
    departureTime: "Heure de Départ",
    arrivalTime: "Heure d'Arrivée",
    timezoneShift: "Décalage Horaire",
    timezoneDesc: "est UTC",
    mealTimesAdjusted: ". Les horaires des repas seront ajustés.",
    selectDishes: "Sélectionnez les plats que vous aimeriez essayer à",
    selected: "sélectionnés",
    discoveringCuisine: "Découverte de la cuisine locale...",
    aiCrafting: "L'IA crée votre plan de repas personnalisé...",
    calories: "Calories",
    protein: "Protéine",
    carbs: "Glucides",
    fat: "Lipides",
    review: "Réviser et Terminer",
    back: "Retour",
    next: "Suivant",
    finish: "Commencer le Voyage",
    planConfirmation: "Confirmation du Plan",
    choosePlanPath: "Choisissez comment poursuivre avec votre plan de repas.",
    continueWithProvidedPlan: "Continuer avec le plan fourni",
    requestLocalDietitianReview: "Demander une vérification par un nutritionniste local",
    simulatingDietitianReview: "Simulation de la vérification nutritionniste...",
    dietitianReviewComplete: "Vérification terminée.",
    reviewedByLocalSpecialist: "Révisé par un spécialiste local.",
    proceedToApp: "Continuer vers l'app",
    noDetailedPlanToReview: "Aucun plan détaillé à vérifier. Vous pouvez quand même continuer.",
    dietitianReviewedSuccessBy: "Révisé avec succès par",
    reviewCompleted: "Vérification terminée",
    nutritionistReviewLabel: "Vérification par nutritionniste local",
    settings: "Paramètres",
    openaiApiKey: "Clé API OpenAI",
    profile: "Profil",
    calTarget: "Cible Cal",
    saveProfile: "Enregistrer le Profil",
    saveAllergies: "Enregistrer les Allergies",
    dangerZone: "Zone de Danger",
    dangerZoneDescription: "Effacer toutes les données locales y compris le profil, les voyages et les journaux de repas.",
    clearAllData: "Effacer Toutes les Données",
    theme: "Thème",
    themeDescription: "Basculer entre le mode clair et sombre.",
    lightMode: "☀️ Mode Clair",
    darkMode: "🌙 Mode Sombre",
    language: "Langue",
    languageDescription: "Choisissez votre langue préférée.",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "Clé configurée",
    
    // Allergy labels
    gluten: "Gluten",
    dairy: "Produits Laitiers",
    eggs: "Œufs",
    peanuts: "Cacahuètes",
    treeNuts: "Fruits à Coque",
    soy: "Soja",
    fish: "Poisson",
    shellfish: "Fruits de Mer",
    wheat: "Blé",
    sesame: "Sésame",
    notKnow: "Je Ne Sais Pas",
    
    // Diet preference labels
    vegetarian: "Végétarien",
    vegan: "Végétalien",
    keto: "Kéto",
    paleo: "Paléo",
    mediterranean: "Méditerranéenne",
    lowCarb: "Faible en Glucides",
    lowFat: "Faible en Lipides",
    halal: "Halal",
    kosher: "Casher",
    noPreference: "Aucune Préférence",
    
    // Custom adding
    addAllergy: "Ajouter une allergie",
    addPreference: "Ajouter une préférence",
    add: "Ajouter",
    alreadyAdded: "Déjà ajouté",
    contains: "Contient",
    allergens: "Allergènes",
    added: "ajouté",
    couldNotGeneratePlan: "Impossible de générer le plan de repas. Utilisation du modèle hors ligne.",
    
    // Navigation
    navHome: "Accueil",
    navTrip: "Voyage",
    navAdd: "Ajouter",
    navLog: "Journal",
    navSettings: "Paramètres",
    welcomeBack: "Bon retour,",
    traveler: "Voyageur",
    kcalRemaining: "kcal restantes",
    water: "Eau",
    steps: "Pas",
    todaysMeals: "Repas d'Aujourd'hui",
    logged: "enregistrés",
    noMealsYet: "Aucun repas enregistré aujourd'hui",
    logFirstMeal: "Enregistrer Votre Premier Repas",
    offPlan: "Hors plan",
    planAdjusted: "Plan Ajusté",
    planAdjustedDesc: "Vous avez eu un repas hors plan. Vos repas restants ont été recalculés pour vous maintenir sur la bonne voie.",
    dailyLog: "Journal Quotidien",
    meals: "Repas",
    activity: "Activité",
    pleaseEnterMealName: "Veuillez entrer le nom du repas",
    negativeValuesError: "Les valeurs nutritionnelles ne peuvent pas être négatives",
    mealLogged: "Repas enregistré !",
    mealRemoved: "Repas supprimé",
    addManualMeal: "Ajouter un Repas Manuel",
    mealName: "Nom du Repas",
    mealType: "Type de Repas",
    breakfast: "Petit Déjeuner",
    lunch: "Déjeuner",
    dinner: "Dîner",
    snack: "Goûter",
    notes: "Notes",
    cancel: "Annuler",
    addMeal: "Ajouter Repas",
    addMealManually: "Ajouter un Repas Manuellement",
    ofTarget: "objectif",
    stepCount: "Nombre de Pas",
    activityLevel: "Niveau d'Activité",
    sedentary: "Sédentaire",
    deskWork: "Travail au bureau",
    lightActivity: "Léger",
    walkingTours: "Promenades",
    moderate: "Modéré",
    hikingCycling: "Randonnée, vélo",
    activeLevel: "Actif",
    sportsIntense: "Sports, intense",
    activityNotes: "Notes d'Activité",
    analyzeMeal: "Analyser le Repas",
    analyzeDesc: "Prenez une photo de votre repas pour une analyse nutritionnelle par IA",
    dishName: "Nom du Plat",
    dishNamePlaceholder: "ex: Coq au Vin, Ratatouille...",
    dishNameOptional: "(optionnel - améliore la précision)",
    analysisMode: "Mode d'Analyse",
    mealPhoto: "Photo de Repas",
    menuPhoto: "Photo du Menu",
    manualEntry: "Saisie Manuelle",
    mealPhotoDesc: "Analyser une photo de votre repas",
    manualEntryDesc: "Enregistrer manuellement les repas, l'eau et l'activité",
    menuPhotoDesc: "Extraire la nutrition d'un menu",
    improvesAccuracy: "Le nom du plat améliore la précision nutritionnelle",
    basedOnCuisine: "Basé sur la cuisine",
    menuDetected: "Éléments du menu détectés",
    selectItemsToLog: "Sélectionnez les articles à enregistrer",
    captureOrUpload: "Capturez ou téléchargez une photo de repas",
    camera: "Caméra",
    uploadPhoto: "Télécharger",
    analyzing: "Analyse en cours...",
    retake: "Reprendre",
    allergenWarning: "Avertissement Allergène",
    detectedIngredients: "Ingrédients Détectés",
    confidence: "confiance",
    logThisMeal: "Enregistrer ce Repas",
    couldNotAnalyze: "Impossible d'analyser la photo. Vérifiez votre clé API dans les Paramètres.",
    pleaseWaitAnalysis: "Veuillez patienter jusqu'à ce que l'analyse en cours soit terminée",
    failedToReadImage: "Impossible de lire le fichier image",
    couldNotLoadDishes: "Impossible de charger les plats locaux. Utilisation des données hors ligne.",
    pleaseCompleteTripDetails: "Veuillez d'abord compléter les détails du voyage",
    mealLoggedSuccess: "Repas enregistré avec succès !",
    allergenDetected: "Allergène détecté",
    noTripPlanned: "Aucun Voyage Planifié",
    noTripDesc: "Complétez la configuration de votre profil pour commencer à planifier votre aventure culinaire.",
    yourTrip: "Votre Voyage",
    activeBadge: "Actif",
    origin: "Origine",
    timezone: "Fuseau Horaire",
    mustTryDishes: "Plats Incontournables",
    mustTryBeverages: "Boissons Incontournables",
    noDishesSelected: "Aucun plat sélectionné.",
    noBeveragesSelected: "Aucune boisson recommandée pour cette destination.",
    alcoholic: "Alcoolisée",
    nonAlcoholic: "Sans alcool",
    worthTrying: "À essayer",
    dailyMealPlan: "Plan de Repas Quotidien",
    apiKeyDescLong: "Nécessaire pour l'analyse de photos de repas, la découverte de plats locaux et la planification de repas par IA. Votre clé est stockée localement dans votre navigateur.",
    allDataCleared: "Toutes les données effacées. Actualisation...",
    
    // Common
    save: "Enregistrer",
    addEntry: "Ajouter Entrée",
    addEntryDesc: "Ajouter repas, eau et activité en utilisant des photos ou saisie manuelle",
    dailySummary: "Résumé Quotidien",
    
    // Welcome Screen
    welcome: "Bienvenue !",
    howWouldYouLikeToBegin: "Comment souhaitez-vous commencer ?",
    startFresh: "Commencer à zéro",
    setUpProfile: "Configurez votre profil et préférences depuis le début. Parfait pour les nouveaux utilisateurs.",
    haveNutritionistPlan: "J'ai un plan de nutritionniste",
    uploadPlanDescription: "Téléchargez votre plan de repas personnalisé de votre nutritionniste pour commencer rapidement.",
    uploading: "Importation...",
    uploadPlan: "Télécharger le plan (JSON)",
    acceptsJsonFormat: "Accepte le format JSON avec les données de profil et de plan de repas",
    downloadSampleFormat: "Télécharger un exemple de format",
    dontWorryAdjustLater: "Ne vous inquiétez pas, vous pourrez toujours ajuster vos préférences plus tard dans les paramètres",
  },
  de: {
    setupProfile: "Lass uns dein Ernährungsprofil einrichten",
    aboutYou: "Über Dich",
    apiKey: "OpenAI API-Schlüssel",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "Erforderlich für Essensplanung und Gerichtentdeckung. Dein Schlüssel wird lokal gespeichert.",
    name: "Name",
    namePlaceholder: "Dein Name",
    age: "Alter",
    sex: "Geschlecht",
    male: "Männlich",
    female: "Weiblich",
    other: "Andere",
    height: "Größe (cm)",
    weight: "Gewicht (kg)",
    goal: "Ziel",
    goalSelectPlaceholder: "Wähle dein Ziel",
    loseWeight: "Gewicht Verlieren",
    maintain: "Halten",
    gainMuscle: "Muskeln Aufbauen",
    allergies: "Allergien & Unverträglichkeiten",
    allergiesDescription: "Wähle alle zutreffenden",
    selectAllergiesDesc: "Wähle alle Allergien oder Lebensmittelunverträglichkeiten. Dies hilft uns, unsichere Gerichte zu markieren.",
    safetyGuardrail: "Sicherheitsschutz Aktiv",
    aiWillNever: "Die KI wird niemals Gerichte empfehlen, die enthalten:",
    preferences: "Präferenzen",
    tripDetails: "Reisedetails",
    localCuisine: "Lokale Küche",
    mealPlan: "Essensplan",
    goals: "Ziele",
    nutritionalGoal: "Ernährungsziel",
    dailyCalorieTarget: "Tägliches Kalorienziel",
    waterTarget: "Wasserziel",
    dietaryPreferences: "Ernährungspräferenzen",
    selectPreferencesDesc: "Wähle deine Ernährungspräferenzen, um die Essensempfehlungen zu personalisieren.",
    departureCity: "Abflugstadt",
    departureCityPlaceholder: "z.B. Berlin",
    destinationCountry: "Zielland",
    selectDestination: "Ziel auswählen",
    departure: "Abflug",
    arrival: "Ankunft",
    departureTime: "Abflugzeit",
    arrivalTime: "Ankunftszeit",
    timezoneShift: "Zeitzonenwechsel",
    timezoneDesc: "ist UTC",
    mealTimesAdjusted: ". Essenszeiten werden angepasst.",
    selectDishes: "Wähle Gerichte, die du probieren möchtest in",
    selected: "ausgewählt",
    discoveringCuisine: "Lokale Küche wird entdeckt...",
    aiCrafting: "KI erstellt deinen personalisierten Essensplan...",
    calories: "Kalorien",
    protein: "Protein",
    carbs: "Kohlenhydrate",
    fat: "Fett",
    review: "Überprüfen & Abschließen",
    back: "Zurück",
    next: "Weiter",
    finish: "Reise Starten",
    planConfirmation: "Planbestätigung",
    choosePlanPath: "Wähle, wie du mit deinem Essensplan fortfahren möchtest.",
    continueWithProvidedPlan: "Mit dem bereitgestellten Plan fortfahren",
    requestLocalDietitianReview: "Prüfung durch lokale Ernährungsberatung anfordern",
    simulatingDietitianReview: "Ernährungsprüfung wird simuliert...",
    dietitianReviewComplete: "Prüfung abgeschlossen.",
    reviewedByLocalSpecialist: "Von einer lokalen Fachkraft geprüft.",
    proceedToApp: "Zur App fortfahren",
    noDetailedPlanToReview: "Kein detaillierter Plan zur Prüfung verfügbar. Du kannst trotzdem fortfahren.",
    dietitianReviewedSuccessBy: "Erfolgreich geprüft von",
    reviewCompleted: "Prüfung abgeschlossen",
    nutritionistReviewLabel: "Lokale Ernährungsprüfung",
    settings: "Einstellungen",
    openaiApiKey: "OpenAI API-Schlüssel",
    profile: "Profil",
    calTarget: "Kal-Ziel",
    saveProfile: "Profil Speichern",
    saveAllergies: "Allergien Speichern",
    dangerZone: "Gefahrenzone",
    dangerZoneDescription: "Alle lokalen Daten löschen, einschließlich Profil, Reisen und Mahlzeitenprotokolle.",
    clearAllData: "Alle Daten Löschen",
    theme: "Thema",
    themeDescription: "Zwischen hellem und dunklem Modus wechseln.",
    lightMode: "☀️ Heller Modus",
    darkMode: "🌙 Dunkler Modus",
    language: "Sprache",
    languageDescription: "Wähle deine bevorzugte Sprache.",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "Schlüssel konfiguriert",
    
    // Allergy labels
    gluten: "Gluten",
    dairy: "Milchprodukte",
    eggs: "Eier",
    peanuts: "Erdnüsse",
    treeNuts: "Baumnüsse",
    soy: "Soja",
    fish: "Fisch",
    shellfish: "Meeresfrüchte",
    wheat: "Weizen",
    sesame: "Sesam",
    notKnow: "Weiß Nicht",
    
    // Diet preference labels
    vegetarian: "Vegetarisch",
    vegan: "Vegan",
    keto: "Keto",
    paleo: "Paläo",
    mediterranean: "Mediterran",
    lowCarb: "Niedrig Kohlenhydrate",
    lowFat: "Fettarm",
    halal: "Halal",
    kosher: "Koscher",
    noPreference: "Keine Präferenz",
    
    // Custom adding
    addAllergy: "Allergie hinzufügen",
    addPreference: "Präferenz hinzufügen",
    add: "Hinzufügen",
    alreadyAdded: "Bereits hinzugefügt",
    contains: "Enthält",
    allergens: "Allergene",
    added: "hinzugefügt",
    couldNotGeneratePlan: "Essensplan konnte nicht generiert werden. Offline-Vorlage wird verwendet.",
    
    // Navigation
    navHome: "Startseite",
    navTrip: "Reise",
    navAdd: "Hinzufügen",
    navLog: "Protokoll",
    navSettings: "Einstellungen",
    welcomeBack: "Willkommen zurück,",
    traveler: "Reisender",
    kcalRemaining: "kcal verbleibend",
    water: "Wasser",
    steps: "Schritte",
    todaysMeals: "Heutige Mahlzeiten",
    logged: "protokolliert",
    noMealsYet: "Heute noch keine Mahlzeiten protokolliert",
    logFirstMeal: "Erste Mahlzeit Protokollieren",
    offPlan: "Außer Plan",
    planAdjusted: "Plan Angepasst",
    planAdjustedDesc: "Du hattest eine außerplanmäßige Mahlzeit. Deine restlichen Mahlzeiten wurden neu berechnet.",
    dailyLog: "Tagesprotokoll",
    meals: "Mahlzeiten",
    activity: "Aktivität",
    pleaseEnterMealName: "Bitte gib den Namen der Mahlzeit ein",
    negativeValuesError: "Nährwerte dürfen nicht negativ sein",
    mealLogged: "Mahlzeit protokolliert!",
    mealRemoved: "Mahlzeit entfernt",
    addManualMeal: "Mahlzeit Manuell Hinzufügen",
    mealName: "Mahlzeitname",
    mealType: "Mahlzeittyp",
    breakfast: "Frühstück",
    lunch: "Mittagessen",
    dinner: "Abendessen",
    snack: "Snack",
    notes: "Notizen",
    cancel: "Abbrechen",
    addMeal: "Mahlzeit Hinzufügen",
    addMealManually: "Mahlzeit Manuell Hinzufügen",
    ofTarget: "Ziel",
    stepCount: "Schrittanzahl",
    activityLevel: "Aktivitätsniveau",
    sedentary: "Sitzend",
    deskWork: "Schreibtischarbeit",
    lightActivity: "Leicht",
    walkingTours: "Spaziergänge",
    moderate: "Moderat",
    hikingCycling: "Wandern, Radfahren",
    activeLevel: "Aktiv",
    sportsIntense: "Sport, intensiv",
    activityNotes: "Aktivitätsnotizen",
    analyzeMeal: "Mahlzeit Analysieren",
    analyzeDesc: "Mach ein Foto deiner Mahlzeit für eine KI-gestützte Nährwertanalyse",
    dishName: "Gerichtname",
    dishNamePlaceholder: "z.B. Schnitzel, Bratwurst...",
    dishNameOptional: "(optional - verbessert die Genauigkeit)",
    analysisMode: "Analysemodus",
    mealPhoto: "Mahlzeit Foto",
    menuPhoto: "Menü Foto",
    manualEntry: "Manuelle Eingabe",
    mealPhotoDesc: "Ein Foto deiner Mahlzeit analysieren",
    manualEntryDesc: "Mahlzeiten, Wasser und Aktivität manuell protokollieren",
    menuPhotoDesc: "Nährwerte aus einem Menü extrahieren",
    improvesAccuracy: "Der Gerichtname verbessert die Nährwertgenauigkeit",
    basedOnCuisine: "Basierend auf Küche",
    menuDetected: "Menüpunkte erkannt",
    selectItemsToLog: "Wähle Elemente zum Protokollieren aus",
    captureOrUpload: "Foto aufnehmen oder hochladen",
    camera: "Kamera",
    uploadPhoto: "Hochladen",
    analyzing: "Analysiere...",
    retake: "Neu aufnehmen",
    allergenWarning: "Allergenwarnung",
    detectedIngredients: "Erkannte Zutaten",
    confidence: "Vertrauen",
    logThisMeal: "Diese Mahlzeit Protokollieren",
    couldNotAnalyze: "Foto konnte nicht analysiert werden. Überprüfe deinen API-Schlüssel in den Einstellungen.",
    pleaseWaitAnalysis: "Bitte warte bis die aktuelle Analyse abgeschlossen ist",
    failedToReadImage: "Bilddatei konnte nicht gelesen werden",
    couldNotLoadDishes: "Lokale Gerichte konnten nicht geladen werden. Verwende Offline-Daten.",
    pleaseCompleteTripDetails: "Bitte vervollständige zuerst die Reisedetails",
    mealLoggedSuccess: "Mahlzeit erfolgreich protokolliert!",
    allergenDetected: "Allergen erkannt",
    noTripPlanned: "Noch Keine Reise Geplant",
    noTripDesc: "Vervollständige dein Profil, um dein kulinarisches Abenteuer zu planen.",
    yourTrip: "Deine Reise",
    activeBadge: "Aktiv",
    origin: "Herkunft",
    timezone: "Zeitzone",
    mustTryDishes: "Gerichte zum Probieren",
    mustTryBeverages: "Empfehlenswerte Getränke",
    noDishesSelected: "Noch keine Gerichte ausgewählt.",
    noBeveragesSelected: "Keine empfohlenen Getränke für dieses Reiseziel.",
    alcoholic: "Alkoholisch",
    nonAlcoholic: "Alkoholfrei",
    worthTrying: "Probierenswert",
    dailyMealPlan: "Täglicher Essensplan",
    apiKeyDescLong: "Erforderlich für Foto-Analyse, lokale Gerichtentdeckung und KI-Essensplanung. Dein Schlüssel wird lokal in deinem Browser gespeichert.",
    allDataCleared: "Alle Daten gelöscht. Aktualisierung...",
    
    // Common
    save: "Speichern",
    addEntry: "Eintrag hinzufügen",
    addEntryDesc: "Mahlzeiten, Wasser und Aktivität mit Fotos oder manueller Eingabe hinzufügen",
    dailySummary: "Tägliche Zusammenfassung",
    
    // Welcome Screen
    welcome: "Willkommen!",
    howWouldYouLikeToBegin: "Wie möchten Sie beginnen?",
    startFresh: "Neu anfangen",
    setUpProfile: "Richten Sie Ihr Profil und Ihre Präferenzen von Grund auf ein. Perfekt für Erstbenutzer.",
    haveNutritionistPlan: "Ich habe einen Ernährungsplan",
    uploadPlanDescription: "Laden Sie Ihren personalisierten Essensplan von Ihrem Ernährungsberater hoch, um schnell zu starten.",
    uploading: "Importiere...",
    uploadPlan: "Plan hochladen (JSON)",
    acceptsJsonFormat: "Akzeptiert JSON-Format mit Profil- und Essensplan-Daten",
    downloadSampleFormat: "Beispielformat herunterladen",
    dontWorryAdjustLater: "Keine Sorge, Sie können Ihre Präferenzen später in den Einstellungen anpassen",
  },
  it: {
    setupProfile: "Configuriamo il tuo profilo nutrizionale",
    aboutYou: "Su di Te",
    apiKey: "Chiave API OpenAI",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "Necessaria per la pianificazione dei pasti e la scoperta di piatti. La tua chiave è memorizzata localmente.",
    name: "Nome",
    namePlaceholder: "Il tuo nome",
    age: "Età",
    sex: "Sesso",
    male: "Maschile",
    female: "Femminile",
    other: "Altro",
    height: "Altezza (cm)",
    weight: "Peso (kg)",
    goal: "Obiettivo",
    goalSelectPlaceholder: "Seleziona il tuo obiettivo",
    loseWeight: "Perdere Peso",
    maintain: "Mantenere",
    gainMuscle: "Guadagnare Muscoli",
    allergies: "Allergie e Intolleranze",
    allergiesDescription: "Seleziona tutte quelle che si applicano",
    selectAllergiesDesc: "Seleziona qualsiasi allergia o intolleranza alimentare. Questo ci aiuta a segnalare piatti non sicuri.",
    safetyGuardrail: "Protezione di Sicurezza Attiva",
    aiWillNever: "L'IA non consiglierà mai piatti contenenti:",
    preferences: "Preferenze",
    tripDetails: "Dettagli del Viaggio",
    localCuisine: "Cucina Locale",
    mealPlan: "Piano Pasti",
    goals: "Obiettivi",
    nutritionalGoal: "Obiettivo Nutrizionale",
    dailyCalorieTarget: "Obiettivo Calorico Giornaliero",
    waterTarget: "Obiettivo d'Acqua",
    dietaryPreferences: "Preferenze Dietetiche",
    selectPreferencesDesc: "Seleziona le tue preferenze dietetiche per personalizzare i consigli sui pasti.",
    departureCity: "Città di Partenza",
    departureCityPlaceholder: "es. Roma",
    destinationCountry: "Paese di Destinazione",
    selectDestination: "Seleziona la destinazione",
    departure: "Partenza",
    arrival: "Arrivo",
    departureTime: "Ora di Partenza",
    arrivalTime: "Ora di Arrivo",
    timezoneShift: "Cambio di Fuso Orario",
    timezoneDesc: "è UTC",
    mealTimesAdjusted: ". Gli orari dei pasti saranno adattati.",
    selectDishes: "Seleziona i piatti che vorresti provare in",
    selected: "selezionati",
    discoveringCuisine: "Scoprendo la cucina locale...",
    aiCrafting: "L'IA sta creando il tuo piano pasti personalizzato...",
    calories: "Calorie",
    protein: "Proteine",
    carbs: "Carboidrati",
    fat: "Grassi",
    review: "Rivedi e Termina",
    back: "Indietro",
    next: "Avanti",
    finish: "Inizia il Viaggio",
    planConfirmation: "Conferma del Piano",
    choosePlanPath: "Scegli come vuoi procedere con il tuo piano pasti.",
    continueWithProvidedPlan: "Continua con il piano fornito",
    requestLocalDietitianReview: "Richiedi verifica nutrizionista locale",
    simulatingDietitianReview: "Simulazione verifica nutrizionista...",
    dietitianReviewComplete: "Verifica completata.",
    reviewedByLocalSpecialist: "Revisionato da uno specialista locale.",
    proceedToApp: "Procedi all'app",
    noDetailedPlanToReview: "Nessun piano dettagliato disponibile per la verifica. Puoi comunque continuare.",
    dietitianReviewedSuccessBy: "Revisionato con successo da",
    reviewCompleted: "Verifica completata",
    nutritionistReviewLabel: "Verifica nutrizionista locale",
    settings: "Impostazioni",
    openaiApiKey: "Chiave API OpenAI",
    profile: "Profilo",
    calTarget: "Obiettivo Cal",
    saveProfile: "Salva Profilo",
    saveAllergies: "Salva Allergie",
    dangerZone: "Zona di Pericolo",
    dangerZoneDescription: "Cancella tutti i dati locali inclusi profilo, viaggi e registri dei pasti.",
    clearAllData: "Cancella Tutti i Dati",
    theme: "Tema",
    themeDescription: "Cambia tra modalità chiara e scura.",
    lightMode: "☀️ Modalità Chiara",
    darkMode: "🌙 Modalità Scura",
    language: "Lingua",
    languageDescription: "Scegli la tua lingua preferita.",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "Chiave configurata",
    
    // Allergy labels
    gluten: "Glutine",
    dairy: "Latticini",
    eggs: "Uova",
    peanuts: "Arachidi",
    treeNuts: "Frutta Secca",
    soy: "Soia",
    fish: "Pesce",
    shellfish: "Frutti di Mare",
    wheat: "Grano",
    sesame: "Sesamo",
    notKnow: "Non So",
    
    // Diet preference labels
    vegetarian: "Vegetariano",
    vegan: "Vegano",
    keto: "Keto",
    paleo: "Paleo",
    mediterranean: "Mediterranea",
    lowCarb: "Basso Contenuto di Carboidrati",
    lowFat: "Basso Contenuto di Grassi",
    halal: "Halal",
    kosher: "Kosher",
    noPreference: "Nessuna Preferenza",
    
    // Custom adding
    addAllergy: "Aggiungi un'allergia",
    addPreference: "Aggiungi una preferenza",
    add: "Aggiungi",
    alreadyAdded: "Già aggiunto",
    contains: "Contiene",
    allergens: "Allergeni",
    added: "aggiunto",
    couldNotGeneratePlan: "Impossibile generare il piano pasti. Utilizzo del modello offline.",
    
    // Navigation
    navHome: "Home",
    navTrip: "Viaggio",
    navAdd: "Aggiungi",
    navLog: "Registro",
    navSettings: "Impostazioni",
    welcomeBack: "Bentornato,",
    traveler: "Viaggiatore",
    kcalRemaining: "kcal rimanenti",
    water: "Acqua",
    steps: "Passi",
    todaysMeals: "Pasti di Oggi",
    logged: "registrati",
    noMealsYet: "Nessun pasto registrato oggi",
    logFirstMeal: "Registra il Primo Pasto",
    offPlan: "Fuori piano",
    planAdjusted: "Piano Adattato",
    planAdjustedDesc: "Hai avuto un pasto fuori piano. I pasti rimanenti sono stati ricalcolati per mantenerti in carreggiata.",
    dailyLog: "Registro Giornaliero",
    meals: "Pasti",
    activity: "Attività",
    pleaseEnterMealName: "Inserisci il nome del pasto",
    negativeValuesError: "I valori nutrizionali non possono essere negativi",
    mealLogged: "Pasto registrato!",
    mealRemoved: "Pasto rimosso",
    addManualMeal: "Aggiungi Pasto Manuale",
    mealName: "Nome del Pasto",
    mealType: "Tipo di Pasto",
    breakfast: "Colazione",
    lunch: "Pranzo",
    dinner: "Cena",
    snack: "Merenda",
    notes: "Note",
    cancel: "Annulla",
    addMeal: "Aggiungi Pasto",
    addMealManually: "Aggiungi Pasto Manualmente",
    ofTarget: "obiettivo",
    stepCount: "Conteggio Passi",
    activityLevel: "Livello di Attività",
    sedentary: "Sedentario",
    deskWork: "Lavoro alla scrivania",
    lightActivity: "Leggero",
    walkingTours: "Passeggiate",
    moderate: "Moderato",
    hikingCycling: "Escursionismo, ciclismo",
    activeLevel: "Attivo",
    sportsIntense: "Sport, intenso",
    activityNotes: "Note di Attività",
    analyzeMeal: "Analizza Pasto",
    analyzeDesc: "Scatta una foto del tuo pasto per un'analisi nutrizionale con IA",
    dishName: "Nome del Piatto",
    dishNamePlaceholder: "es: Risotto, Carbonara...",
    dishNameOptional: "(opzionale - migliora la precisione)",
    analysisMode: "Modalità di Analisi",
    mealPhoto: "Foto del Pasto",
    menuPhoto: "Foto del Menu",
    manualEntry: "Inserimento Manuale",
    mealPhotoDesc: "Analizza una foto del tuo pasto",
    manualEntryDesc: "Registra manualmente pasti, acqua e attività",
    menuPhotoDesc: "Estrai la nutrizione da un menu",
    improvesAccuracy: "Il nome del piatto migliora la precisione nutrizionale",
    basedOnCuisine: "Basato sulla cucina",
    menuDetected: "Elementi del menu rilevati",
    selectItemsToLog: "Seleziona gli articoli da registrare",
    captureOrUpload: "Cattura o carica una foto del pasto",
    camera: "Fotocamera",
    uploadPhoto: "Carica",
    analyzing: "Analisi in corso...",
    retake: "Ripeti",
    allergenWarning: "Avviso Allergene",
    detectedIngredients: "Ingredienti Rilevati",
    confidence: "affidabilità",
    logThisMeal: "Registra Questo Pasto",
    couldNotAnalyze: "Impossibile analizzare la foto. Controlla la tua chiave API nelle Impostazioni.",
    pleaseWaitAnalysis: "Attendere il completamento dell'analisi in corso",
    failedToReadImage: "Impossibile leggere il file immagine",
    couldNotLoadDishes: "Impossibile caricare i piatti locali. Utilizzo dati offline.",
    pleaseCompleteTripDetails: "Si prega di completare prima i dettagli del viaggio",
    mealLoggedSuccess: "Pasto registrato con successo!",
    allergenDetected: "Allergene rilevato",
    noTripPlanned: "Nessun Viaggio Pianificato",
    noTripDesc: "Completa la configurazione del tuo profilo per iniziare a pianificare la tua avventura culinaria.",
    yourTrip: "Il Tuo Viaggio",
    activeBadge: "Attivo",
    origin: "Origine",
    timezone: "Fuso Orario",
    mustTryDishes: "Piatti da Provare",
    mustTryBeverages: "Bevande da Provare",
    noDishesSelected: "Nessun piatto selezionato ancora.",
    noBeveragesSelected: "Nessuna bevanda consigliata per questa destinazione.",
    alcoholic: "Alcolica",
    nonAlcoholic: "Analcolica",
    worthTrying: "Da provare",
    dailyMealPlan: "Piano Pasti Giornaliero",
    apiKeyDescLong: "Necessaria per l'analisi di foto dei pasti, la scoperta di piatti locali e la pianificazione dei pasti con IA. La tua chiave è memorizzata localmente nel tuo browser.",
    allDataCleared: "Tutti i dati cancellati. Aggiornamento...",
    
    // Common
    save: "Salva",
    addEntry: "Aggiungi Voce",
    addEntryDesc: "Aggiungi pasti, acqua e attività usando foto o inserimento manuale",
    dailySummary: "Riepilogo Giornaliero",
    
    // Welcome Screen
    welcome: "Benvenuto!",
    howWouldYouLikeToBegin: "Come vorresti iniziare?",
    startFresh: "Inizia da zero",
    setUpProfile: "Configura il tuo profilo e le preferenze da zero. Perfetto per i nuovi utenti.",
    haveNutritionistPlan: "Ho un piano nutrizionista",
    uploadPlanDescription: "Carica il tuo piano pasti personalizzato dal tuo nutrizionista per iniziare rapidamente.",
    uploading: "Importazione...",
    uploadPlan: "Carica piano (JSON)",
    acceptsJsonFormat: "Accetta formato JSON con dati profilo e piano pasti",
    downloadSampleFormat: "Scarica formato di esempio",
    dontWorryAdjustLater: "Non preoccuparti, puoi sempre regolare le tue preferenze più tardi nelle impostazioni",
  },
  zh: {
    setupProfile: "让我们设置您的营养档案",
    aboutYou: "关于您",
    apiKey: "OpenAI API密钥",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "AI餐饮规划和菜肴发现所需。您的密钥将本地存储。",
    name: "姓名",
    namePlaceholder: "您的姓名",
    age: "年龄",
    sex: "性别",
    male: "男性",
    female: "女性",
    other: "其他",
    height: "身高 (cm)",
    weight: "体重 (kg)",
    goal: "目标",
    goalSelectPlaceholder: "选择您的目标",
    loseWeight: "减重",
    maintain: "保持",
    gainMuscle: "增肌",
    allergies: "过敏和不耐受",
    allergiesDescription: "选择所有适用项",
    selectAllergiesDesc: "选择任何过敏或食物不耐受。这有助于我们标记不安全的菜肴。",
    safetyGuardrail: "安全保护已激活",
    aiWillNever: "AI永远不会推荐包含以下成分的菜肴：",
    preferences: "偏好",
    tripDetails: "旅行详情",
    localCuisine: "当地美食",
    mealPlan: "餐饮计划",
    goals: "目标",
    nutritionalGoal: "营养目标",
    dailyCalorieTarget: "每日卡路里目标",
    waterTarget: "水摄入目标",
    dietaryPreferences: "饮食偏好",
    selectPreferencesDesc: "选择您的饮食偏好以个性化餐饮推荐。",
    departureCity: "出发城市",
    departureCityPlaceholder: "例如 北京",
    destinationCountry: "目的地国家",
    selectDestination: "选择目的地",
    departure: "出发",
    arrival: "到达",
    departureTime: "出发时间",
    arrivalTime: "到达时间",
    timezoneShift: "时区变化",
    timezoneDesc: "是UTC",
    mealTimesAdjusted: "。用餐时间将被调整。",
    selectDishes: "选择您想在以下地点尝试的菜肴",
    selected: "已选择",
    discoveringCuisine: "发现当地美食...",
    aiCrafting: "AI正在创建您的个性化餐饮计划...",
    calories: "卡路里",
    protein: "蛋白质",
    carbs: "碳水化合物",
    fat: "脂肪",
    review: "审查并完成",
    back: "返回",
    next: "下一步",
    finish: "开始旅程",
    planConfirmation: "计划确认",
    choosePlanPath: "选择您希望如何继续您的餐饮计划。",
    continueWithProvidedPlan: "继续使用当前计划",
    requestLocalDietitianReview: "请求当地营养师审核",
    simulatingDietitianReview: "正在模拟营养师审核...",
    dietitianReviewComplete: "审核完成。",
    reviewedByLocalSpecialist: "已由当地专家审核。",
    proceedToApp: "进入应用",
    noDetailedPlanToReview: "暂无可审核的详细计划，您仍可继续。",
    dietitianReviewedSuccessBy: "已由以下人员成功审核：",
    reviewCompleted: "审核完成",
    nutritionistReviewLabel: "当地营养师审核",
    settings: "设置",
    openaiApiKey: "OpenAI API密钥",
    profile: "个人资料",
    calTarget: "卡路里目标",
    saveProfile: "保存个人资料",
    saveAllergies: "保存过敏信息",
    dangerZone: "危险区域",
    dangerZoneDescription: "清除所有本地数据，包括个人资料、旅行和餐饮记录。",
    clearAllData: "清除所有数据",
    theme: "主题",
    themeDescription: "在浅色和深色模式之间切换。",
    lightMode: "☀️ 浅色模式",
    darkMode: "🌙 深色模式",
    language: "语言",
    languageDescription: "选择您的首选语言。",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "密钥已配置",    
    // Allergy labels
    gluten: "麸质",
    dairy: "乳制品",
    eggs: "鸡蛋",
    peanuts: "花生",
    treeNuts: "坚果",
    soy: "大豆",
    fish: "鱼",
    shellfish: "贝类",
    wheat: "小麦",
    sesame: "芝麻",
    notKnow: "不知道",
    
    // Diet preference labels
    vegetarian: "素食",
    vegan: "纯素",
    keto: "生酮",
    paleo: "原始饮食",
    mediterranean: "地中海饮食",
    lowCarb: "低碳水化合物",
    lowFat: "低脂",
    halal: "清真",
    kosher: "犹太洁食",
    noPreference: "无偏好",
    
    // Custom adding
    addAllergy: "添加过敏原",
    addPreference: "添加偏好",
    add: "添加",
    alreadyAdded: "已添加",
    contains: "包含",
    allergens: "过敏原",
    added: "已添加",
    couldNotGeneratePlan: "无法生成餐食计划。使用离线模板。",
    
    // Navigation
    navHome: "首页",
    navTrip: "旅行",
    navAdd: "添加",
    navLog: "记录",
    navSettings: "设置",
    welcomeBack: "欢迎回来，",
    traveler: "旅行者",
    kcalRemaining: "千卡剩余",
    water: "饮水",
    steps: "步数",
    todaysMeals: "今日餐食",
    logged: "已记录",
    noMealsYet: "今天还没有记录餐食",
    logFirstMeal: "记录第一餐",
    offPlan: "计划外",
    planAdjusted: "计划已调整",
    planAdjustedDesc: "您有一餐偏离了计划。剩余餐食已重新计算以保持您在正轨上。",
    dailyLog: "每日记录",
    meals: "餐食",
    activity: "活动",
    pleaseEnterMealName: "请输入餐食名称",
    negativeValuesError: "营养值不能为负数",
    mealLogged: "餐食已记录！",
    mealRemoved: "餐食已移除",
    addManualMeal: "手动添加餐食",
    mealName: "餐食名称",
    mealType: "餐食类型",
    breakfast: "早餐",
    lunch: "午餐",
    dinner: "晚餐",
    snack: "零食",
    notes: "备注",
    cancel: "取消",
    addMeal: "添加餐食",
    addMealManually: "手动添加餐食",
    ofTarget: "目标",
    stepCount: "步数计数",
    activityLevel: "活动水平",
    sedentary: "久坐",
    deskWork: "办公室工作",
    lightActivity: "轻度",
    walkingTours: "步行游览",
    moderate: "中等",
    hikingCycling: "徒步、骑行",
    activeLevel: "活跃",
    sportsIntense: "运动、高强度",
    activityNotes: "活动备注",
    analyzeMeal: "分析餐食",
    analyzeDesc: "拍摄餐食照片进行AI营养分析",
    dishName: "菜名",
    dishNamePlaceholder: "例如：宫保鸡丁、麻婆豆腐...",
    dishNameOptional: "(可选 - 提高准确性)",
    analysisMode: "分析模式",
    mealPhoto: "餐食照片",
    menuPhoto: "菜单照片",
    manualEntry: "手动输入",
    mealPhotoDesc: "分析您的餐食照片",
    manualEntryDesc: "手动记录餐食、水和活动",
    menuPhotoDesc: "從菜單中提取營養信息",
    improvesAccuracy: "菜名可提高营养准确性",
    basedOnCuisine: "基于菜系",
    menuDetected: "检测到的菜单项",
    selectItemsToLog: "选择要记录的项目",
    captureOrUpload: "拍摄或上传餐食照片",
    camera: "相机",
    uploadPhoto: "上传",
    analyzing: "分析中...",
    retake: "重拍",
    allergenWarning: "过敏原警告",
    detectedIngredients: "检测到的成分",
    confidence: "置信度",
    logThisMeal: "记录此餐",
    couldNotAnalyze: "无法分析照片。请在设置中检查您的API密钥。",
    pleaseWaitAnalysis: "请等待当前分析完成",
    failedToReadImage: "无法读取图像文件",
    couldNotLoadDishes: "无法加载当地菜肴。使用离线数据。",
    pleaseCompleteTripDetails: "请先完成旅行详情",
    mealLoggedSuccess: "餐食记录成功！",
    allergenDetected: "检测到过敏原",
    noTripPlanned: "尚未计划旅行",
    noTripDesc: "完成您的个人资料设置以开始规划您的美食之旅。",
    yourTrip: "您的旅行",
    activeBadge: "进行中",
    origin: "出发地",
    timezone: "时区",
    mustTryDishes: "必尝菜肴",
    mustTryBeverages: "推荐饮品",
    noDishesSelected: "尚未选择菜肴。",
    noBeveragesSelected: "此目的地暂无推荐饮品。",
    alcoholic: "含酒精",
    nonAlcoholic: "无酒精",
    worthTrying: "值得尝试",
    dailyMealPlan: "每日餐饮计划",
    apiKeyDescLong: "用于餐食照片分析、本地菜肴发现和AI餐饮规划。您的密钥存储在浏览器本地。",
    allDataCleared: "所有数据已清除。正在刷新...",
    
    // Common
    save: "保存",
    addEntry: "添加条目",
    addEntryDesc: "使用照片或手动输入添加餐食、水分和活动",
    dailySummary: "每日摘要",
    
    // Welcome Screen
    welcome: "欢迎！",
    howWouldYouLikeToBegin: "您希望如何开始？",
    startFresh: "全新开始",
    setUpProfile: "从头开始设置您的个人资料和偏好。非常适合新用户。",
    haveNutritionistPlan: "我有营养师计划",
    uploadPlanDescription: "上传您从营养师那里获得的个性化餐食计划以快速开始。",
    uploading: "导入中...",
    uploadPlan: "上传计划（JSON）",
    acceptsJsonFormat: "接受包含个人资料和餐食计划数据的JSON格式",
    downloadSampleFormat: "下载示例格式",
    dontWorryAdjustLater: "不用担心，您可以在设置中随时调整您的偏好",
  },
  ja: {
    setupProfile: "栄養プロフィールを設定しましょう",
    aboutYou: "あなたについて",
    apiKey: "OpenAI APIキー",
    apiKeyPlaceholder: "sk-...",
    apiKeyDescription: "AI食事計画と料理発見に必要です。キーはローカルに保存されます。",
    name: "名前",
    namePlaceholder: "あなたの名前",
    age: "年齢",
    sex: "性別",
    male: "男性",
    female: "女性",
    other: "その他",
    height: "身長 (cm)",
    weight: "体重 (kg)",
    goal: "目標",
    goalSelectPlaceholder: "目標を選択",
    loseWeight: "減量",
    maintain: "維持",
    gainMuscle: "筋肉増強",
    allergies: "アレルギーと不耐性",
    allergiesDescription: "該当するものをすべて選択",
    selectAllergiesDesc: "アレルギーや食物不耐性を選択してください。これにより、安全でない料理を警告します。",
    safetyGuardrail: "安全保護が有効",
    aiWillNever: "AIは以下を含む料理を推奨しません：",
    preferences: "好み",
    tripDetails: "旅行の詳細",
    localCuisine: "地元料理",
    mealPlan: "食事計画",
    goals: "目標",
    nutritionalGoal: "栄養目標",
    dailyCalorieTarget: "1日のカロリー目標",
    waterTarget: "水分摂取目標",
    dietaryPreferences: "食事の好み",
    selectPreferencesDesc: "食事の好みを選択して、食事の推奨をパーソナライズします。",
    departureCity: "出発都市",
    departureCityPlaceholder: "例 東京",
    destinationCountry: "目的地の国",
    selectDestination: "目的地を選択",
    departure: "出発",
    arrival: "到着",
    departureTime: "出発時刻",
    arrivalTime: "到着時刻",
    timezoneShift: "タイムゾーンの変更",
    timezoneDesc: "はUTC",
    mealTimesAdjusted: "。食事時間が調整されます。",
    selectDishes: "試してみたい料理を選択してください",
    selected: "選択済み",
    discoveringCuisine: "地元料理を発見中...",
    aiCrafting: "AIがパーソナライズされた食事計画を作成中...",
    calories: "カロリー",
    protein: "タンパク質",
    carbs: "炭水化物",
    fat: "脂肪",
    review: "確認して完了",
    back: "戻る",
    next: "次へ",
    finish: "旅を始める",
    planConfirmation: "プラン確認",
    choosePlanPath: "食事プランの進め方を選択してください。",
    continueWithProvidedPlan: "提示されたプランで続行",
    requestLocalDietitianReview: "現地栄養士の確認を依頼",
    simulatingDietitianReview: "栄養士確認をシミュレーション中...",
    dietitianReviewComplete: "確認が完了しました。",
    reviewedByLocalSpecialist: "現地の専門家による確認済み。",
    proceedToApp: "アプリへ進む",
    noDetailedPlanToReview: "確認できる詳細プランがありませんが、このまま続行できます。",
    dietitianReviewedSuccessBy: "次の担当者による確認が完了しました:",
    reviewCompleted: "確認完了",
    nutritionistReviewLabel: "現地栄養士による確認",
    settings: "設定",
    openaiApiKey: "OpenAI APIキー",
    profile: "プロフィール",
    calTarget: "カロリー目標",
    saveProfile: "プロフィールを保存",
    saveAllergies: "アレルギーを保存",
    dangerZone: "危険ゾーン",
    dangerZoneDescription: "プロフィール、旅行、食事記録を含むすべてのローカルデータを消去します。",
    clearAllData: "すべてのデータを消去",
    theme: "テーマ",
    themeDescription: "ライトモードとダークモードを切り替えます。",
    lightMode: "☀️ ライトモード",
    darkMode: "🌙 ダークモード",
    language: "言語",
    languageDescription: "お好みの言語を選択してください。",
    english: "English",
    portuguese: "Português",
    spanish: "Español",
    french: "Français",
    german: "Deutsch",
    italian: "Italiano",
    chinese: "中文",
    japanese: "日本語",
    keyConfigured: "キーが設定されました",
    
    // Allergy labels
    gluten: "グルテン",
    dairy: "乳製品",
    eggs: "卵",
    peanuts: "ピーナッツ",
    treeNuts: "ナッツ類",
    soy: "大豆",
    fish: "魚",
    shellfish: "甲殻類",
    wheat: "小麦",
    sesame: "ごま",
    notKnow: "わからない",
    
    // Diet preference labels
    vegetarian: "ベジタリアン",
    vegan: "ビーガン",
    keto: "ケト",
    paleo: "パレオ",
    mediterranean: "地中海式",
    lowCarb: "低炭水化物",
    lowFat: "低脂肪",
    halal: "ハラール",
    kosher: "コーシャ",
    noPreference: "無し",
    
    // Custom adding
    addAllergy: "アレルギーを追加",
    addPreference: "好みを追加",
    add: "追加",
    alreadyAdded: "既に追加済み",
    contains: "含有",
    allergens: "アレルゲン",
    added: "追加しました",
    couldNotGeneratePlan: "食事プランを生成できませんでした。オフラインテンプレートを使用します。",
    
    // Navigation
    navHome: "ホーム",
    navTrip: "旅行",
    navAdd: "追加",
    navLog: "記録",
    navSettings: "設定",
    welcomeBack: "おかえりなさい、",
    traveler: "旅行者",
    kcalRemaining: "kcal 残り",
    water: "水分",
    steps: "歩数",
    todaysMeals: "今日の食事",
    logged: "記録済み",
    noMealsYet: "今日はまだ食事が記録されていません",
    logFirstMeal: "最初の食事を記録する",
    offPlan: "計画外",
    planAdjusted: "計画を調整",
    planAdjustedDesc: "計画外の食事がありました。残りの食事は目標達成のために再計算されました。",
    dailyLog: "毎日の記録",
    meals: "食事",
    activity: "活動",
    pleaseEnterMealName: "食事名を入力してください",
    negativeValuesError: "栄養値は負の値にできません",
    mealLogged: "食事が記録されました！",
    mealRemoved: "食事が削除されました",
    addManualMeal: "手動で食事を追加",
    mealName: "食事名",
    mealType: "食事タイプ",
    breakfast: "朝食",
    lunch: "昇食",
    dinner: "夕食",
    snack: "間食",
    notes: "メモ",
    cancel: "キャンセル",
    addMeal: "食事を追加",
    addMealManually: "手動で食事を追加",
    ofTarget: "目標",
    stepCount: "歩数カウント",
    activityLevel: "活動レベル",
    sedentary: "座りがち",
    deskWork: "デスクワーク",
    lightActivity: "軽い",
    walkingTours: "ウォーキング",
    moderate: "中程度",
    hikingCycling: "ハイキング、サイクリング",
    activeLevel: "活発",
    sportsIntense: "スポーツ、高強度",
    activityNotes: "活動メモ",
    analyzeMeal: "食事を分析",
    analyzeDesc: "食事の写真を撮ってAI栄養分析を行います",
    dishName: "料理名",
    dishNamePlaceholder: "例：寿司、ラーメン...",
    dishNameOptional: "(オプション - 精度が向上します)",
    analysisMode: "分析モード",
    mealPhoto: "食事写真",
    menuPhoto: "メニュー写真",
    manualEntry: "手動入力",
    mealPhotoDesc: "食事の写真を分析する",
    manualEntryDesc: "食事、水分、活動を手動で記録",
    menuPhotoDesc: "メニューから栄養情報を抽出",
    improvesAccuracy: "料理名は栄養精度を向上させます",
    basedOnCuisine: "料理に基づく",
    menuDetected: "検出されたメニュー項目",
    selectItemsToLog: "記録するアイテムを選択",
    captureOrUpload: "食事の写真を撮影またはアップロード",
    camera: "カメラ",
    uploadPhoto: "アップロード",
    analyzing: "分析中...",
    retake: "撮り直す",
    allergenWarning: "アレルゲン警告",
    detectedIngredients: "検出された成分",
    confidence: "信頼度",
    logThisMeal: "この食事を記録",
    couldNotAnalyze: "写真を分析できませんでした。設定でAPIキーを確認してください。",
    pleaseWaitAnalysis: "現在の分析が完了するまでお待ちください",
    failedToReadImage: "画像ファイルの読み取りに失敗しました",
    couldNotLoadDishes: "地元料理を読み込めませんでした。オフラインデータを使用します。",
    pleaseCompleteTripDetails: "まず旅行の詳細を完成させてください",
    mealLoggedSuccess: "食事が正常に記録されました！",
    allergenDetected: "アレルゲン検出",
    noTripPlanned: "まだ旅行の計画がありません",
    noTripDesc: "プロフィール設定を完了して、料理の冒険を始めましょう。",
    yourTrip: "あなたの旅",
    activeBadge: "アクティブ",
    origin: "出発地",
    timezone: "タイムゾーン",
    mustTryDishes: "おすすめ料理",
    mustTryBeverages: "おすすめドリンク",
    noDishesSelected: "まだ料理が選択されていません。",
    noBeveragesSelected: "この目的地におすすめの飲み物はありません。",
    alcoholic: "アルコール",
    nonAlcoholic: "ノンアルコール",
    worthTrying: "試す価値",
    dailyMealPlan: "毎日の食事計画",
    apiKeyDescLong: "食事写真分析、現地料理の発見、AI食事計画に必要です。キーはブラウザにローカル保存されます。",
    allDataCleared: "すべてのデータが消去されました。更新中...",
    
    // Common
    save: "保存",
    addEntry: "エントリーを追加",
    addEntryDesc: "写真または手動入力を使用して食事、水分、活動を追加",
    dailySummary: "日次サマリー",
    
    // Welcome Screen
    welcome: "ようこそ！",
    howWouldYouLikeToBegin: "どのように始めたいですか？",
    startFresh: "新規作成",
    setUpProfile: "プロフィールと設定をゼロからセットアップします。初回ユーザーに最適です。",
    haveNutritionistPlan: "管理栄養士のプランがあります",
    uploadPlanDescription: "管理栄養士からのパーソナライズされた食事プランをアップロードして素早く始めましょう。",
    uploading: "インポート中...",
    uploadPlan: "プランをアップロード（JSON）",
    acceptsJsonFormat: "プロフィールと食事プランデータを含むJSON形式を受け付けます",
    downloadSampleFormat: "サンプル形式をダウンロード",
    dontWorryAdjustLater: "心配いりません。設定でいつでもお好みを調整できます",
  }
}

export function t(key: keyof typeof translations.en, lang?: Language): string {
  const language = lang || getLanguage()
  return translations[language][key] || translations.en[key]
}
